### ISSUE TITLE
v-tooltip not work 

### ISSUE THREAD

**Issue by Fornori** [Akryum/v-tooltip#104]
Hello, I use the next command:
Vue.directive('v-tooltip', VTooltip);
Vue.directive('close-popover', VClosePopover);
Vue.component('v-popover', VPopover);

And after this <span v-tooltip="msg">Hover me</span>
And after render it render simple <spam>Hover me</span>

What I do wrong?

**Comment by mrv1k** [comment]
Check your imports and make sure your vue instance is active when you declare directive/component.
```javascript
import Vue from 'vue'
import { VTooltip, VPopover, VClosePopover } from 'v-tooltip'**

Vue.directive('tooltip', VTooltip)
Vue.directive('close-popover', VClosePopover)
Vue.component('v-popover', VPopover)
```

**Comment by Akryum** [comment]
Did you add some CSS to the tooltips? ([doc](https://github.com/Akryum/v-tooltip#getting-started))
