### ISSUE TITLE
Trigger click and hiding using a delay

### ISSUE THREAD

**Issue by rico** [Akryum/v-tooltip#105]
I try to hide a tooltip after a specific delay, when the user has clicked the element:

`v-tooltip="{ content: 'Copied!', trigger: 'click', delay: {hide: 1000} }"`

However, the tooltip does not disappear. Any idea?

**Comment by Akryum** [comment]
Use `manual` trigger and the `show` option ([doc](https://github.com/Akryum/v-tooltip#other-options)).

**Comment by rico** [comment]
Ok, thanks.
