### ISSUE TITLE
Problem in long tooltip text without white space .

### ISSUE THREAD

**Issue by aminp** [Akryum/v-tooltip#107]
Hi, 
When I add a long text to the tooltip content, tooltip content will getting out from the right side of browser window.
![tooltip](https://user-images.githubusercontent.com/3415182/36898334-79220518-1e2b-11e8-8ccf-50ef302b319f.jpg)

Please find an attachment.

**Comment by Akryum** [comment]
Use the [word-break](https://developer.mozilla.org/fr/docs/Web/CSS/word-break) CSS property.
