### ISSUE TITLE
Customize order in placement option

### ISSUE THREAD

**Issue by vhsmoke** [Akryum/v-tooltip#111]
It wolud be great if there will be possibility to set order for placement tooltip.
For example: now I can set `{ placement: 'top' }` or `{ placement: 'auto' }`. 
And I want to set an array if priority, something like that: `{ placement: ['top', 'left', 'auto'] }`.
So if tooltip will go outside window, it will replaced in custom priority.

**Comment by Mattyon** [comment]
+1
It's actually [supported by Popper.js](https://github.com/FezVrasta/popper.js/blob/master/docs/_includes/popper-documentation.md#Popper.placements).

**Comment by Mattyon** [comment]
@Akryum: Any progress with this feature? Or is there a chance to do it on my own and get your PR approval? Thanks!

**Comment by ivansieder** [comment]
Aren't you actually able to do that with the popperOptions property? Just passing an array with your placements to the placements property of popperOptions?

**Comment by ivansieder** [comment]
The thing you are trying to do is to define, in which direction the popover/tooltip shold primarily move, if it's about to overflow. Right? Wouldn't this solve your issue?
```javascript
{
    // Other options
    popperOptions: {
        preventOverflow: {
            priority: ['left','right','top','bottom']
        }
    }
}
```

**Comment by Mattyon** [comment]
This might be a solution in some cases, but not in the case you have a popover targeted to an element which might be anywhere on the page and you need to specify where to render if it can't fit.

Currently, the popover will move, but it'll be rendered above the target element, so the user can't see from where it's open. From the UX perspective, it's just a wrong design, which could be solved only by making the `placement`(s) property an array.

**Comment by Mattyon** [comment]
I don't think it's worth creating an online example. The feature request is clear and the need of that too.
... We just need to specify where to place the popover once it won't fit the page in a controlled order, which is possible within popper.js itself, but not with this wrapper.

**Comment by ivansieder** [comment]
@Mattyon did you ever hear about codesandbox.io? provides .vue file support out of the box

**Comment by Mattyon** [comment]
@ivansieder: Yes, I tried. Got an error with a loader, then [checked out their examples](https://codesandbox.io/s/z2lz94oqk4) (more than just this one), but found nothing than .js files. But I guess we are slightly off the topic here anyway.

I understand what you mean. If there is a _possible way_, let's just do it. But constructing complex JSON object to modify `PopperJs` properties instead of built-in support is just an **ugly** solution which shall not be recommended. And for sure not used if possible (therefore this ticket).

... Besides. If it's supported, why to limit it to a single position?

**Comment by Akryum** [comment]
> +1
> It's actually [supported by Popper.js](https://github.com/FezVrasta/popper.js/blob/master/docs/_includes/popper-documentation.md#Popper.placements) [](/FezVrasta/popper.js/blob/HEAD@{2018-08-08T08:29:38Z}/docs/_includes/popper-documentation.md#Popper.placements).

It's actually not supported by popper this way, you linked the `Popper.placements` constant which is provided by popper for reference.

**Comment by Akryum** [comment]
Adding a modifier to `popperOptions` is the right way to do it (see [docs](https://github.com/FezVrasta/popper.js/blob/master/docs/_includes/popper-documentation.md#modifiers..preventOverflow.priority). Since we are not going to implement a short for every Popper modifier, I'm closing this.
