### ISSUE TITLE
Add style examples to package

### ISSUE THREAD

**Issue by tu4mo** [Akryum/v-tooltip#119]
Could you add the style examples as files in the package, so one could just import them instead of copy-pasting?

**Comment by Akryum** [comment]
Then 99% of the time you'll need to change them, right?

**Comment by tu4mo** [comment]
I would simply override the properties I needed. This would also simplify upgrading if you ever needed to make changes to the HTML structure.

**Comment by Akryum** [comment]
Implemented in v3 alpha
