### ISSUE TITLE
Could not view the popover on clicking a button!

### ISSUE THREAD

**Issue by harishankards** [Akryum/v-tooltip#120]
Hi, I'm using your package in my project. Such a great work. Thanks for that.

Currently, I'm trying [this](https://github.com/Akryum/v-tooltip#component). On click the button, nothing happens visually. But I'm able to see that `v-popover open` and `v-popover` classes are changing over the popover div.

I guess it's something related to design as my project uses bootstrap. Hence, I used the code below:

```js
 import Vue from 'vue'
  import { VTooltip, VPopover, VClosePopover } from 'v-tooltip'

  Vue.directive('tooltip', VTooltip)
  Vue.directive('close-popover', VClosePopover)
  Vue.component('v-popover', VPopover)

  VTooltip.options.defaultTemplate =
    '<div class="foo" role="tooltip"><div class="tooltip-arrow"></div><div class="tooltip-inner"></div></div>'
  
```

and my HTML part goes like below:
```html
<v-popover offset="16">
            <button class="tooltip-target b3">Click me</button>

            <template slot="popover">
              <input class="tooltip-content" placeholder="Tooltip content" />
              <p>
                hello
              </p>
              <a v-close-popover>Close</a>
            </template>
          </v-popover>

```

**Comment by nicollis** [comment]
yeah I'm not sure if I have the same issue or not. However on RC.31 I was preforming e2e testing and verifying the tooltip by using a JS click event to get the tooltip to appear in the DOM then used Nightwatch to verify the content. 

However in RC.32 clicking to make the tooltip appear on click seems to be broken and now the e2e test are failing. I'm not sure how to do the test anymore and we have frozen our project on RC.31 until its fixed or we work out another solution.

**Comment by harishankards** [comment]
@nicollis, thanks for the update. Looking forward!

**Comment by weerdm** [comment]
Yes, it blocks all the clicking events.

**Comment by nicollis** [comment]
Same here. I tooltip that can't be e2e tested isn't one we can use in professional projects. Not to mention blocking click events kills mobile friendliness.

**Comment by Akryum** [comment]
Use the `hideOnTargetClick` option: https://github.com/Akryum/v-tooltip#other-options and https://github.com/Akryum/v-tooltip#global-options

**Comment by rockmandash** [comment]
This issue should be reopened, `hideOnTargetClick` goes to the `$attrs` in `Popover.vue`, so it isn't working.
