### ISSUE TITLE
boundariesElement prop type

### ISSUE THREAD

**Issue by palpich** [Akryum/v-tooltip#121]
In Popper.js Documentation `boundariesElement` prop can get String type [link](https://popper.js.org/popper-documentation.html#modifiers..preventOverflow.boundariesElement)

Could you update `boundariesElement` prop type in v-tooltip?

**Comment by scniro** [comment]
@Akryum why close this? Seems sensible. Also there is a lacking of documentation that states what is expected for `boundariesElement`. Is it a ref, a raw dom element, a query selector? Vote to repoen...
