### ISSUE TITLE
Why use span elements?

### ISSUE THREAD

**Issue by gooqiao** [Akryum/v-tooltip#123]
When invoked using the v-popover component mode,for example:
``` vue
  <v-popover offset="16" :disabled="!isEnabled"> 

   <div class="tooltip-box"> 
    <input type="text" :value="keyword" /> 
    <button class="tooltip-target b3">Click me</button> 
   </div> 

   <template slot="popover"> 
    <examplecomponent char="=" /> 
    <a v-close-popover="">Close</a> 
   </template> 

  </v-popover>
```
The compiled result is:
``` html
<div data-v-6755199a="" class="v-popover open"> 

   <span aria-describedby="popover_q9yq2dlrn4" class="trigger" style="display: inline-block;"> 

    <div data-v-6755199a="" class="tooltip-box"> 
     <input type="text" :value="keyword" /> 
     <button data-v-6755199a="" class="tooltip-target b3 popover-btn">Click me</button> 
    </div>

   </span> 

</div>
```
Notice the parent element of the `.tooltip-box`.
He is a `span` element.
This does not comply with the HTML specification.
Should use `div` element instead.
Thank you!

**Comment by patrickabkarian** [comment]
an inline-block as span is html spec

**Comment by arkhamvm** [comment]
Any news? `span` breaks SSR hydration.

**Comment by AndyDyer** [comment]
@arkhamvm  have you made any progress on this, running into the same issue with v-tooltip breaking SSR hydration. Though I cant see this documented anywhere so I am wondering if their is something obvious I am missing

**Comment by arkhamvm** [comment]
> @arkhamvm have you made any progress on this, running into the same issue with v-tooltip breaking SSR hydration. Though I cant see this documented anywhere so I am wondering if their is something obvious I am missing

There is docs with example (with missing `<tbody>`) :
https://ssr.vuejs.org/guide/hydration.html#hydration-caveats
Any not valid html breaks hydration, so if you put any `<div>` in `<span>` - it's breaks :(

**Comment by arkhamvm** [comment]
@AndyDyer Also you can see warnings in console in development mode. As temporary solution i wrap `v-popover` into `no-ssr` tag.
