### ISSUE TITLE
Showing a tooltip for a disabled button

### ISSUE THREAD

**Issue by alexeden** [Akryum/v-tooltip#125]
I've got a use-case where I need to show a tooltip for a button, specifically when that button is in a disabled state. When the button is disabled, the tooltip refuses to show. Is there an option somewhere that I need to configure to allow this? 

JSFiddle repro:
https://jsfiddle.net/2vxn0op7/

**Comment by nik-el** [comment]
+1
same issue

**Comment by ivansieder** [comment]
Hi @alexeden and @nik-el, sorry for the delay, but it's been a bit busy the last weeks. The point with this is, that it's actually not an issue related to v-tooltip, but a browser-specification. Depending on the browser you use, some might and some other might not emit events for disabled elements. In this case, Firefox seems to emit events for disabled buttons and chrome doesn't.

As a workaround you might wrap the button in a div to be able to use v-tooltip on it.

**Comment by ishaiavrahami** [comment]
is there a solution yet ?
