### ISSUE TITLE
IE9 error `requestAnimationFrame` is undefined

### ISSUE THREAD

**Issue by hafez-bsup** [Akryum/v-tooltip#126]
I get these errors on IE9:

```
SCRIPT5009: 'requestAnimationFrame' is undefined
SCRIPT5009: 'cancelAnimationFrame' is undefined
```

Any workaround?

**Comment by ivansieder** [comment]
Hi @hafez-bsup, requestAnimationFrame and cancelAnimationFrame are not supported in IE9. This is actually nothing related to v-tooltip. But you could try to use a polyfill to "fake" the native Browser API if it is not present.

**Comment by mrquokka** [comment]
> Hi @hafez-bsup, requestAnimationFrame and cancelAnimationFrame are not supported in IE9. This is actually nothing related to v-tooltip. But you could try to use a polyfill to "fake" the native Browser API if it is not present.
Can you add this information to readme file?

**Comment by mrquokka** [comment]
Also need Promise. That is horrible, waste time for nothing
