### ISSUE TITLE
Allow setting popover container to false

### ISSUE THREAD

**Issue by tu4mo** [Akryum/v-tooltip#127]
I'd like for popover always to appear on the parent element for accessibility reasons.

https://github.com/Akryum/v-tooltip/blob/15af3762b1dc9a346b3e3b9ea0890f27b4e7be83/src/components/Popover.vue#L416

This should be possible by setting the container to `false`, but currently its prop type doesn't allow booleans.

**Comment by andrewdds** [comment]
I'm curious why this was closed. Seems like setting `container='false'` should work, but it throws a warning `No container for popover`.

**Comment by andrewdds** [comment]
Ah never mind, I realized you need to `v-bind:container='false'` otherwise it just defines it as the string "false".

Is this documented anywhere?
