### ISSUE TITLE
Binding tooltip  in ES6 template string ?

### ISSUE THREAD

**Issue by arifhussain353** [Akryum/v-tooltip#13]
I generate some dynamically html content where i want to add tooltip.This html is inside `Es6 template string` format.In `ES6 template string`  we use `grave` symbol on keyboard.Is there any way to use 'v-tooltip` attribute inside template string ?

Such as :

```javascript
let htmlContent = `<div class="popover" role="tooltip"> <i v-tooltip.top-center=" 'Remove' "></i> </div>` 
```

**Comment by Akryum** [comment]
I think this should work.

**Comment by arifhussain353** [comment]
@Akryum  I use this code for `bootstrap popover` but it's not working for me .

**Comment by Akryum** [comment]
Is it inside a Vue component `template`?

**Comment by arifhussain353** [comment]
Yes inside `mounted` and render html on load.

**Comment by Akryum** [comment]
Could you please make a reproduction example (like a JSFiddle)?

**Comment by arifhussain353** [comment]
Ya sure but right now i am in office i can send you Screenshot for my code.But i will make JSFiddle also later .Is it ok  ?

**Comment by Akryum** [comment]
Okay :smile:

**Comment by arifhussain353** [comment]
@Akryum  here is  https://jsfiddle.net/arifhussain/vja7rcam/10/ .I guess the problem is  `bootstrap popover`  dom render on click and `vue-tooltip`  does not find this dom on load?

**Comment by arifhussain353** [comment]
Any solution yet?

**Comment by Akryum** [comment]
You have conflicts with Bootstrap CSS. Please upgrade to the latest version and customize the v-tooltip classes.
