### ISSUE TITLE
Tooltip transition doesn't show after first show

### ISSUE THREAD

**Issue by controversial** [Akryum/v-tooltip#132]
Using the example CSS from the README, the transition on the tooltip only shows for entrance on the first time it's displayed. After the mouse is removed from the tooltip, `display: none` is immediately added to the element and there's no chance for the transition to be applied

**Comment by willashley23** [comment]
I also have this problem, and it is blocking us from being able to adopt this library 😢

**Comment by Akryum** [comment]
Sorry I can't reproduce in the demo.

**Comment by ivansieder** [comment]
@controversial and @willashley23 do you have any code sample to reproduce this?

**Comment by henrikdahl** [comment]
@controversial @willashley23 It's because your tooltip css `.tooltip` lacks `display: block !important` :v

Now I'm not sure why it's coded to be required, feels redundant to me, but that's the issue nonetheless.

**Comment by Akryum** [comment]
You may also have another library conflicting, try to change the classes in the default templates.
