### ISSUE TITLE
Tooltip not rendering in some cases

### ISSUE THREAD

**Issue by jcasale** [Akryum/v-tooltip#134]
I am using v-tooltip v2.0.0-rc.33 with vue v2.5.x, I have a site that I cannot get the tooltip to render, to test I created the following component:
```html
<template>
  <div>
    <p v-tooltip="msg">Hover me</p>
  </div>
</template>

<script>
  import { VTooltip } from 'v-tooltip'
  export default {
    name: "ToolTipTest",
    directives: {
      tooltip: VTooltip
    },
    data() {
      return {
        msg: "Tooltip message"
      };
    }
  };
</script>

<style scoped>
</style>
```

In a `vue-cli` generated template, this component produces a tooltip that renders as expected, but in another larger site I have, it does not. How can I debug the non working site? Do you have any suggestions what may cause this?

**Comment by nwaughachukwuma** [comment]
Not working for me also, @Akryum you might need to tailor the readme more than it currently is. Nice package but we need to be able to use it. Thanks

**Comment by jcasale** [comment]
Turns out to be a css inheritance issue, the tooltip was activating however it was off the view. I switched to [vue-directive-tooltip](https://hekigan.github.io/vue-directive-tooltip/) which did not succumb to existing layout and worked fine.
