### ISSUE TITLE
How to remove outline from span?

### ISSUE THREAD

**Issue by exwizzard** [Akryum/v-tooltip#138]
![image](https://user-images.githubusercontent.com/1271688/43959520-6ba90e92-9caf-11e8-971c-8aac5e4e2b77.png)

As you can see on the image, there is a blue outline when I click on the popover element, I fixed this by adding this css:

```
.trigger {
  outline: 0;
}
```

I was wondering if there is a better way or a prop that handles this?

**Comment by ivansieder** [comment]
Hi @exwizzard, generally removing the outline of an element removes some accessibility from your page, as users who can't use a mouse or have a visual impairment are being excluded from using your site.

Also, this is more related to your own use-case, so the change should happen on your website (as you've shown in css above), it's not something the plugin should take care of.

**Comment by exwizzard** [comment]
@ivansieder I already have outlines on my own CSS code. We are talking about this plugin adding its own outline CSS, the .trigger class is a class from this plugin.

**Comment by ivansieder** [comment]
Hi @exwizzard, the plugin itself does not add any outlines. Outlines are default css behaviour and are being added by the browser automatically.

**Comment by exwizzard** [comment]
The outlines are added because this plugin has `tabindex="-1"` on the tag that has the .trigger class, I forgot what it was exactly since its an old issue, but now I checked it on the demo page.

![image](https://user-images.githubusercontent.com/1271688/44653525-4eda3000-a9ef-11e8-88a9-0394a6f7e8b7.png)

The main reason why I opened this issue is because the outlines only show in chrome but not in firefox or edge, because like you said the browser adds their outlines. These outlines from chrome look completely different than my own outlines, different color and shape.

**Comment by ivansieder** [comment]
Hi @exwizzard, the tabindex only defines the order in which the elements should be focused when pressing the tab key on your keyboard for example. It's only indirectly related to the outline you have shown in the code above.

I have tested this on the latest Chrome, Edge and Firefox on Windows 10 and as far as I can tell, the outlines won't be shown in any of these browsers for me.

You should be able to style the outline property with css properly and tabindex shouldn't interfere with that. If that's not the case, please provide a link to a codesandbox or some sort of online editor so I can test it, where it doesn't work for you as it should.

**Comment by exwizzard** [comment]
@ivansieder The outline shows up when you click on it as well, on the specific demo above you have to click the edge between the outline and the circle. I never had a problem with styling anything, this problem was solved for me even before I opened the issue.

Here is the codesandbox demo, open it on chrome and click on the text. Its rough but it shows exactly what I am talking about.

https://codesandbox.io/s/v80l269v53

![image](https://user-images.githubusercontent.com/1271688/44656517-7504cd80-a9f9-11e8-802f-35c26571dc10.png)
