### ISSUE TITLE
How to stop recreating content element?

### ISSUE THREAD

**Issue by imudin** [Akryum/v-tooltip#139]
Hello!
Thanks for the nice work!

I am using html content which includes video and iframe.
When I change the tooltip-target position, it seems destroying the html content and binding it again everytime.
Video and iframe urls are loading over and over.

How to solve it?

**Comment by ivansieder** [comment]
Hi @imudin, do you have any code sample ready to demonstrate clearer, what exactly you mean?

**Comment by imudin** [comment]
Hello @ivansieder! thank you for your considering.
Yes, Ive just made sample [here](https://jsfiddle.net/tsjco74e/1944/).
When I checked the source code of v-tooltip, the method `bind` is  calling as the position is changed.
I am not sure if it is supposed to be like this. it would be good if I could use this.
So far,  I am using `v-popover` which is working well.

**Comment by ivansieder** [comment]
Yes, I would go for v-popover, as that also allows you to use components inside of it. Does the v-popover have the behaviour you expect it to have?

**Comment by imudin** [comment]
@ivansieder Yes v-popover is working well as I expected, thank you

**Comment by ivansieder** [comment]
Perfect, so if this is resolved for you, I'd like to ask you, if the issue could possibly be closed? :)
