### ISSUE TITLE
Load component on activation

### ISSUE THREAD

**Issue by Mestika** [Akryum/v-tooltip#140]
I'm using the popover to show some information to the user which is fetched from backend. I'm using the v-popover component with a custom component as template/slot for this.

Instead of loading all my components and fetching all data I want to only load the custom component or only fetch data, when popover is active and visible.

How is that possible, if at all?

I cannot listen for events on my child custom component and the component is loaded and mounted right away when the page loads for all `v-popover` components so all fetches is processed right away on page load.

**Comment by Akryum** [comment]
You can load the data after the popover is open.

**Comment by Mestika** [comment]
Please, how I would do that?
The child-component has no way of listening to the events of the v-popover, only the parent?

**Comment by xeboo** [comment]
Is there an example for this if the popover is to be loaded as an extra component?

**Comment by mofolo** [comment]
Bit of an old thread but thought I might add my 2 cents. 

What you can do is something like this:

```
<v-popover @show="load()" >
<a class="btn">Load</a>
<MyComponent slot="popover" :data="info"/>
</v-popover>

```
Then use the method `load()` to call the data into your `info` model and render within your component.
