### ISSUE TITLE
local transformations are overridden by translate3d

### ISSUE THREAD

**Issue by willashley23** [Akryum/v-tooltip#141]
We want to make our tooltips appear with transition where they move slightly up/down/left/right from the origin, which we would accomplish by simply applying styles like this:

```css
transition: transform 500ms ease;
transform: translateY(-16px);
```

However this does not work as the tooltip is positioned near its target by using `translate3D`, which is applied as an inline style, thus overriding our local styles. 

For example:
```css
transform: translate3d(640px, -48px, 0px);
```

Using `!important` is not ideal and wouldn't even solve the issue because the library depends on this `translate3d` in order to position the element in the first place. In the docs, the only properties transitioned in examples are `opacity` and `visibility`. Is there any way around this?

**Comment by Akryum** [comment]
You can animate the `.wrapper` of popover (if you need one on tooltips, you can change the html template).

**Comment by fabio-ferreira** [comment]
I didn't understand how exactly I would achieve it by changing the html template on tooltips.
