### ISSUE TITLE
Placement issue on component

### ISSUE THREAD

**Issue by ChucKN0risK** [Akryum/v-tooltip#144]
I have a component created via a `v-for` loop on which I have set the v-tooltip like so:

```html
<div
    v-tooltip="{
        trigger: 'hover',
        placement: 'top-start',
        delay: { show: 450, hide: 100 }
    }"
>
```
The issue is that the first tooltip generated has a different placement from the other ones:

My component list without tooltip on each component:
<img width="272" alt="screen shot 2018-08-29 at 15 09 52" src="https://user-images.githubusercontent.com/3913276/44789742-b1712e80-ab9d-11e8-9064-20813cc60b45.png">

My component list with tooltip on each component:
<img width="272" alt="screen shot 2018-08-29 at 15 09 42" src="https://user-images.githubusercontent.com/3913276/44789791-d1a0ed80-ab9d-11e8-8827-6307bafc3c1a.png">

The tooltip DOM:
<img width="623" alt="screen shot 2018-08-29 at 15 10 10" src="https://user-images.githubusercontent.com/3913276/44789821-e2516380-ab9d-11e8-9aba-1b0eefd02e8c.png">

Why has the first tooltip a placement of 'bottom-start' whereas I explicitely initiate the tooltip with a `top-start` placement?

Thanks in advance 😉

**Comment by ivansieder** [comment]
Hi @ChucKN0risK, have you placed the component list at the edge of the browser? If so, this is the  behaviour of popper.js (the library, v-tooltip is based on) to avoid that tooltips/popovers get get outside the viewport. This makes sure, that even if normally your tooltip would be outside the viewport, it's still visible, even if positioned differently.

I suppose this is mostly related to preventOverflow (coming from popper.js) https://popper.js.org/popper-documentation.html#modifiers..preventOverflow

**Comment by ChucKN0risK** [comment]
My list is inside a sidebar like so ;) I don't think we could consider this as the edge of the browser.

![img](https://user-images.githubusercontent.com/3913276/44839467-26e10b80-ac3f-11e8-9c81-0cfc92cd3fc7.png)

**Comment by ivansieder** [comment]
Alright, you are using Bootstrap I suppose. Right? Is there any chance you could provide a codesandbox example with the code inside, otherwise it's difficult to debug this furtherin this specific case.

Just for curiosity, could you try changing the code to the following?
```html
<div
    v-tooltip="{
        trigger: 'hover',
        placement: 'top-start',
        delay: { show: 450, hide: 100 },
        popperOptions: {
            preventOverflow: false
        }
    }"
>
```

**Comment by ChucKN0risK** [comment]
It's not Bootstrap. It's a tool I'm currently building. It will allow designers/developers to manage base variables for the digital product they're working on 😉

I changed the code as you proposed but it didn't solve my issue. I'll make a codesandbox asap.

Thanks again for helping me!

**Comment by ivansieder** [comment]
yes, I suppose it's something related to the preventOverflow. But as soon as you have the codesandbox ready, I'll happily look into it!

**Comment by ChucKN0risK** [comment]
Ok I figured what is happening. The first element's tooltip is displayed at the bottom because it is sticked at the top of the parent container. I added a `padding-top` on my parent container and this time the tooltip was displayed on `top` as requested. 

<img width="241" alt="screen shot 2018-09-28 at 10 42 11" src="https://user-images.githubusercontent.com/3913276/46197868-484f1900-c30b-11e8-8b42-132138a701ae.png">

<img width="240" alt="screen shot 2018-09-28 at 10 42 36" src="https://user-images.githubusercontent.com/3913276/46197884-4d13cd00-c30b-11e8-9a28-c763202858a7.png">

How can I override this behavior ?

**Comment by ivansieder** [comment]
Try looking at https://popper.js.org/popper-documentation.html#modifiers..preventOverflow, that might be, what you're looking for. you can pass popperOptions along with v-tooltip, too

**Comment by Akryum** [comment]
You can change `boundaryElement` or the `defaultBoundariesElement` global option (for example, `document.body`).

**Comment by ChucKN0risK** [comment]
Thanks @Akryum !

```
Vue.use(VTooltip, {
  defaultBoundariesElement: document.body,
});
```

It now works like a charm!

**Comment by Hansfelix50** [comment]
> Thanks @Akryum !
> 
> ```
> Vue.use(VTooltip, {
>   defaultBoundariesElement: document.body,
> });
> ```
> 
> It now works like a charm!

Please add this to docs. I wasted time to search it

**Comment by kardeepak77** [comment]
I am using Vue3 and still have this problem. My Tooltip is still shown at the bottom of the page. Have tried suggestions mentioned above. 

Here is my vue file - 
<template>
  <h1>Tooltip demo</h1>

  <div
    v-tooltip="{
      trigger: 'hover',
      placement: 'top-start',
      delay: { show: 450, hide: 100 },
      content: '<b>Hey</b>, how are <i>you</i>?',
      html: true,
      popperOptions: {
        preventOverflow: false,
      },
    }"
  >
    Tooltip demo
  </div>
</template>

main.js

import { default as FloatingVue } from 'floating-vue'
import VTooltip from 'floating-vue'

app.use(FloatingVue)
app.use(VTooltip, {
    defaultBoundariesElement: document.body,
  })
