### ISSUE TITLE
Placement strangely works

### ISSUE THREAD

**Issue by DenniLa2** [Akryum/v-tooltip#147]
http://take.ms/BWuOZ
Some element in different environments behaves differently. In modal 'top' and 'auto' work as 'bottom' and 'left' as 'right' . I don`t know, how to reproduce and what influences this behavior.

**Comment by ivansieder** [comment]
Hi @DenniLa2, do you have any code example which shows where and how that issue occours? This is probably related to the preventOverflow property, but it's hard for me to tell without any code sample.

**Comment by DenniLa2** [comment]
Hi @ivansieder, I copied part of project in new project and can not reproduce this behavior (( I think I'll have to accept this

**Comment by ivansieder** [comment]
Means that it works in the new, copied project as it should?

**Comment by DenniLa2** [comment]
Yes.
