### ISSUE TITLE
Disable repositioning (placement="bottom" > placement="top") when resize screen

### ISSUE THREAD

**Issue by dbomfim** [Akryum/v-tooltip#148]
Guys, first of all, thanks for the helpful component! 
After read the documents and see the examples, I didn't found a way to disable repositioning a bottom element to top, when resizing the screen. Is it possible?!
Tks

**Comment by ivansieder** [comment]
Hi @dbomfim, you mean that you have an element positioned to the bottom, but it gets repositioned to the top, if you resize your window?

**Comment by dbomfim** [comment]
Yes!

**Comment by dbomfim** [comment]
I want it to always be have the x-placement="bottom".

**Comment by ivansieder** [comment]
Did you try adding the following option to the v-tooltip?
```javascript
popperOptions: {
  preventOverflow: {
    enabled: false
  }
}
```

**Comment by dbomfim** [comment]
I'll try that, thank you!

**Comment by ivansieder** [comment]
No worries. Let me know, if you still have issues with that. Eventually also post a completer code sample so it's easier to test it for your situation.

**Comment by njleonzhang** [comment]
```
tipOptions: {
        content: 'xxxxx',
        defaultPlacement: 'top',
        show: true,
        delay: {
          hide: 3000,
          show: 0
        },
        trigger: 'manual',
        offset: 8,
        popperOptions: {
          preventOverflow: {
            enabled: false
          }
        }
      },

      <div class="mp-reward-hand" v-tooltip.top-center='tipOptions'>
```

This seems can not work now in version 2.0.2, I don't want the top reposition when scrolling.

**Comment by Hansfelix50** [comment]
It doesn´t work still
