### ISSUE TITLE
tooltip isnt displayed on dynamically rendered elements

### ISSUE THREAD

**Issue by egeersoz** [Akryum/v-tooltip#15]
```
<p>
    <span class="item" v-for="item in list" v-tooltip="item.owner">{{ item.body }}</span>
</p>
```

With this setup, the tooltip works fine. However, `list` is actually a computed property:

```
computed: {
    list() {
        return this.some.other.list
    }
}
```

If `this.some.other.list` changes, `list` is updated and a new `item` is rendered, but it doesn't get a tooltip.

Is there a way to "initialize" tooltips on newly rendered items?

**Comment by SaMiCoOo** [comment]
Well and easy work around

1. Make a separate component of your dynamically rendered item
```html
<template>
    <span class="item"  v-tooltip="item.owner">{{ item.body }}</span>
</template>

<script>
export default {
 name: 'separate'
 props: ['item']
}
```
2. Then parent component
```html
``<p>
    <separate class="item" :item="item" v-for="item in list" v-tooltip="item.owner"></separate>
</p>
```

I know it's a hassle but you can do this for now.

**Comment by huifengshi** [comment]
@SaMiCoOo ,tried your solution,still not work.

**Comment by Akryum** [comment]
Is this still the case with the latest version?

**Comment by juanvillegas** [comment]
It's not a problem with the Tooltip plugin, it is just how Vue works...

**Comment by Akryum** [comment]
Those concerned should try keying their loop items.
