### ISSUE TITLE
No possibility for raw tag displaying

### ISSUE THREAD

**Issue by defusioner** [Akryum/v-tooltip#150]
**Current behaviour**:
It is not possible to pass `content: "<number><regex>"`, to the popover, as they will be translated as html tags and won't be displayed.

**Expected**: Display raw tags.

P.S. Maybe I've lost some skills to google ? Thx

**Comment by ivansieder** [comment]
Hi @defusioner, this is by design (https://github.com/Akryum/v-tooltip#other-options). Try using the following piece of code: `{ content: '<number><regex>', html: false }` to insert the content as innerText instead of innerHTML. That will avoid that the text is being inserted as HTML.

**Comment by defusioner** [comment]
@ivansieder Thank you! I was trying to pass `html: false` to the initializer when I register the component to Vue. I should have done with `defaultHtml: false`

**Comment by mokkabonna** [comment]
This is really bad as a default value. Values should by default escape HTML, this is a security risk.

Frameworks have by default behaviour to escape HTML, and you have to explicitly turn it off if you want to display possible unsafe content.
