### ISSUE TITLE
Popup breaks after route change

### ISSUE THREAD

**Issue by archSeer** [Akryum/v-tooltip#151]
If the popup is open (or was focused at least once), and the route changes, the component will lose track of the popup DOM and stop rendering.

Usecase: I have a search menu in the header that shows a popup with a list of items.

```
<header>
  <!-- popup here -->
</header>
<router-view/>
```

**Comment by archSeer** [comment]
A bit more detail, it seems to be unrelated to routes.

If you have the popup open, then click outside the popup, the popup will close and it's internal isOpen will get set to false, but the prop `open` will continue to be true. Only way to fix it is to toggle open to false manually.

I ended up doing `@auto-hide="open = false"` to reset the prop.

**Comment by Akryum** [comment]
Why don't you use the `update:open` event or the `open.sync=""` prop modifier? ([doc](https://github.com/Akryum/v-tooltip#popover-component-reference))
