### ISSUE TITLE
Scoped style doesn't work

### ISSUE THREAD

**Issue by kapdom** [Akryum/v-tooltip#154]
Hi.
I have a problem with styles. When I mark style a scoped then v-tooltip doesn't come out at all. Only works when use style as a global.
But I need two different style in two separates components so how to fix that scoped problem?
I use it as a plugin.

Pleas advice. 
Thank you.

**Comment by CurtisBelt** [comment]
I think the dynamic class option is what you're looking for.

https://github.com/Akryum/v-tooltip#dynamic-css-classes


> ### Dynamic CSS classes
> 
> You can set the tooltip css classes dynamically with the object notation:
> 
> ```html
> <button v-tooltip="{ content: 'You have ' + count + ' new messages.', classes: ['a', 'b'] }">
> ```
> 
> This will replace the default CSS classe with 'a b' on the tooltip element.
> 
> You can also use the standard class notation:
> 
> ```html
> <button v-tooltip="{ content: 'You have ' + count + ' new messages.', classes: 'a b' }">
> ```
> 
> Or a reactive property:
> 
> ```html
> <button v-tooltip="{ content: 'You have ' + count + ' new messages.', classes: tooltipClasses }">
> ```

**Comment by javillerenas** [comment]
@CurtisBelt do you have any suggestions for when someone is using `v-tooltip` as a directive in one part and `v-tooltip` as a component inside a Vue component, and want to style both differently?

Currently I have the same problem as the one mentioned by this issue. 

If I set the style to `scoped` inside the Vue Component where I am using the `v-tooltip` as a component, it does not work. And if I delete the `scoped`, it changes the look of the `v-tooltip` being used as a directive.

**Comment by CurtisBelt** [comment]
@javillerenas Did you try specifying a custom class on the directive?

**Comment by javillerenas** [comment]
@CurtisBelt Actually I did and it solved my problem. Thank you!

**Comment by Akryum** [comment]
Tooltip content is not part of the component template, so it's not scoped by the template compiler.

**Comment by aislanmaia** [comment]
I'm having the same problem right now. I need two different popovers and one style affects another. It seems only global styles are applied correctly.

**Comment by worlanyodamalie** [comment]
Sorry this might be late, but a workaround would be for you to define your own custom wrapper class using the popoverWrapperClass prop  for the popover component  and then CSS styles can be applied specifically to that class

> I'm having the same problem right now. I need two different popovers and one style affects another. It seems only global styles are applied correctly.

**Comment by HasanKadi** [comment]
@worlanyodamalie @aislanmaia  @Akryum 

i am having the issue now and trying to get multiple popovers with diffrent styles with one global style .

when i am setting the popoverWrapperClass="my-popover-wrapper"
                   popoverInnerClass="my-popover-inner"
                   
 but the style in those classes are not applied  to the component 
 
 did any body has an Idee why this is not working 
  note: in Chrome inspector style changen is working 
  
  .my-popover-wrapper {
  background: red;
}

.my-popover-inner {
  width: 10px;
}



  <v-popover placement="bottom-end"
                   offset="0"
                   :container="false"
                   popoverWrapperClass="data-selection-button-group-wrapper"
                   popoverInnerClass="data-selection-button-group-inner"
        >
          <Button class="action-button action-list">...</Button>
          <template slot="popover">
            <Button> T1</Button>
            <br>
            <Button> T2</Button>
            <br>
            <Button v-close-popover> Close</Button>
          </template>
        </v-popover>


![image](https://user-images.githubusercontent.com/46930321/114218760-2027e280-996a-11eb-8e66-08930d3c54d6.png)

> Sorry this might be late, but a workaround would be for you to define your own custom wrapper class using the popoverWrapperClass prop for the popover component and then CSS styles can be applied specifically to that class
> 
> > I'm having the same problem right now. I need two different popovers and one style affects another. It seems only global styles are applied correctly.

**Comment by HasanKadi** [comment]
<v-popover placement="bottom-end"
                   offset="0"
                   :container="false"
                   popoverWrapperClass="data-selection-button-group-wrapper"
                   popoverInnerClass="data-selection-button-group-inner"
        >
          <Button class="action-button action-list">...</Button>
          <template slot="popover">
            <Button> T1</Button>
            <br>
            <Button> T2</Button>
            <br>
            <Button v-close-popover> Close</Button>
          </template>
        </v-popover>

**Comment by HasanKadi** [comment]
`   <v-popover placement="bottom-end"
                   offset="0"
                   :container="false"
                   popoverWrapperClass="data-selection-button-group-wrapper"
                   popoverInnerClass="data-selection-button-group-inner"
        >
          <Button class="action-button action-list">...</Button>
          <template slot="popover">
            <Button> T1</Button>
            <br>
            <Button> T2</Button>
            <br>
            <Button v-close-popover> Close</Button>
          </template>
        </v-popover>`
