### ISSUE TITLE
Accessibility feature: Escape key should close any open tooltip

### ISSUE THREAD

**Issue by sbenyoub-accor** [Akryum/v-tooltip#159]
Hi,

When a user is navigating a page with the keyboard they will see the tooltips open when the element receives focus/ click ... but the tooltip will not close until the user repeat the previous trigger on that element. This is not optimal for keyboard navigation because the tooltip may be covering something that the user wants to see and the only way for them to close the tooltip is to navigate to the next tab stop.

It is a common convention that the escape key will close any open modal or overlay items, so the escape key should close tooltips as well.

**Comment by Akryum** [comment]
Implemented.
