### ISSUE TITLE
Delayed elements are visible on quick move over

### ISSUE THREAD

**Issue by rottmann** [Akryum/v-tooltip#16]
Set a defaultDelay: e.g. 1000
When you have 3 elements with a tooltip and you move over from the 1st to 2nd to 3rd element in less then 1000ms, all tooltips appear after each other.

Need a clearTimeout when leave an element.

**Comment by mbarwick83** [comment]
Any update on this?

**Comment by blyleven** [comment]
Would be great if this could be fixed. 👍

**Comment by Akryum** [comment]
This is likely a popperjs issue.

**Comment by Akryum** [comment]
If you still have this issue, I suggest re-opening it in the popper.js repo.

**Comment by fergardi** [comment]
I'm having this issue too.

**Comment by Akryum** [comment]
This should be fixed in the latest release: https://github.com/Akryum/v-tooltip/releases/tag/v2.0.0-rc.6

**Comment by Akryum** [comment]
You can try the demo page, the second button has a delayed tooltip: https://akryum.github.io/v-tooltip/#/

**Comment by mbarwick83** [comment]
Trying to set the delay globally, but it's not working. What am I missing?

```
Vue.use(VTooltip, { 
	delay: {
    	show: 5000,
    	hide: 0,
	}
});
```
