### ISSUE TITLE
Popover positioning problem tranform: translate3d

### ISSUE THREAD

**Issue by nattyluke** [Akryum/v-tooltip#162]
I have a long popover component.
When there is no space at the bottom( for example devtools open), my popover moves up (under the navigation)
I realised there is a dynamic inline style changing from:
transform: translate3d(1639px, 43px, 0px);
to 
transform: translate3d(1639px, 5px, 0px);

Do i have control over this property? I want the second value always stay 43px.
(I guess the first value is the width of my window which has to stay dynamic)
If I overwrite the style, the width will be static, and my popup width is not positioned right anymore.

**Comment by nattyluke** [comment]
https://github.com/Akryum/v-tooltip/issues/141
This helped me

**Comment by nattyluke** [comment]
Does not work

**Comment by Akryum** [comment]
Use the offset option.
