### ISSUE TITLE
How to add tooltips on the fly?

### ISSUE THREAD

**Issue by tuomassalo** [Akryum/v-tooltip#166]
I have a case where I need to add tooltips to e.g. all `<h2>` tags in dynamic content:

    <div v-html="someHtmlThatContainsH2Tags"/>

I'm using `v-tooltip` in other parts of the project, so I'd like to also use it in this case, but I haven't found a way to add tooltips dynamically. I understand this might be considered out of scope, because this is not a Vue-style thing.

    // I fancy something like this:
    this.$tooltip.add(h2DomElement, { content: 'You have ' + count + ' new messages.' })

**Comment by Akryum** [comment]
> I understand this might be considered out of scope, because this is not a Vue-style thing.

Pretty much! :smile_cat:
