### ISSUE TITLE
Allow override of the "open" class in Popover.vue

### ISSUE THREAD

**Issue by javillerenas** [Akryum/v-tooltip#170]
In `Popover.vue`, there is no way to override the `.open` class that gets added when triggered, and which has a default background of `#e7e7e7`.

This is problematic in situations where the element that is a target has a non-rectangular shape (i.e. a circle png image) [see image below].

![image](https://user-images.githubusercontent.com/17650062/49242839-9b535400-f3c0-11e8-99fe-94b9e7d787c5.png)

**Comment by cassiebrooks** [comment]
Hi @javillerenas, I made a PR to remove the default `open` class a few months ago - see https://github.com/Akryum/v-tooltip/pull/156
