### ISSUE TITLE
v-popover vs. vuetify sloted component

### ISSUE THREAD

**Issue by royprigat** [Akryum/v-tooltip#172]
Versions and Environment
Vuetify: 1.3.12
Vue: 2.5.17
v-tooltip: 2.0.0-rc33

Steps to reproduce
Have the popover slot with a Vuetify component such as v-checkbox or v-range-slider

Expected Behavior
Normal functionality of the v-popover with the sloted component inside

Actual Behavior
Vuetify components have a delay when closing the v-popover, and they don't work properly.

Reproduction Link
https://codesandbox.io/s/lpm863vq3m

**Comment by Akryum** [comment]
cc @johnleider

**Comment by johnleider** [comment]
Something in the container is stopping the mouse move event. You can see this by either clicking on the track (works as expected) or clicking on the dot, leave the mouse pressed down, move it below outside of the container and move it left to right.
![slider](https://user-images.githubusercontent.com/9064066/57385027-47227c00-7177-11e9-8320-0f7fa05a38e7.gif)

**Comment by Akryum** [comment]
After looking at `VSlider` source code, I think the issue is that the `mousemove` event is listened on the vuetify app element, but the popper instance is added on the `<body>`, so it's not triggering the `mousemove` listener.

**Comment by Akryum** [comment]
For v-tooltip 2.x:

```
Vue.use(VTooltip, {
  popover: {
    defaultContainer: "[data-app]"
  }
})
```

https://codesandbox.io/s/2opo3lkrp

---

For v-tooltip 3.x:

```
Vue.use(VTooltip, {
  container: '[data-app]'
})
```

https://codesandbox.io/s/7yx8r59nkj

**Comment by yeokyeong** [comment]
thank you so much!

**Comment by Cyclodex** [comment]
I used the components directly and solved the problem this way:

```
import * as FloatingVue from "floating-vue";

FloatingVue.options.container = "[data-app]";

Vue.component("FVDropdown", FloatingVue.Dropdown);
Vue.component("FVTooltip", FloatingVue.Tooltip);
```
