### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by cairoramos7** [Akryum/v-tooltip#173]
In the [dynamic classes](https://github.com/Akryum/v-tooltip#dynamic-css-classes) part the documentation could be updated.
For example, I was implementing as in the example documentation:
**1.** 
`<button v-tooltip="{ content: 'You have ' + count + ' new messages.', classes: ['a', 'b'] }">`
**2.**
`<button v-tooltip="{ content: 'You have ' + count + ' new messages.', classes: 'a b' }">`
**3.** 
`<button v-tooltip="{ content: 'You have ' + count + ' new messages.', classes: tooltipClasses }">`

But for me it worked like this (for example):
`<button v-tooltip="{ content: 'You have ' + count + ' new messages.', class: tooltipClasses }">`

**Comment by Akryum** [comment]
I don't understand. The document uses are valid.
