### ISSUE TITLE
Resize event triggering improperly

### ISSUE THREAD

**Issue by albertodeago** [Akryum/v-tooltip#174]
Hi all, 
Thanks for the amazing work done,
When v-popover is opened and the content has not enough space, it looks like the event 'resize' is triggered a lot of times and I don't think it's the correct behaviour.

Reproduced on chrome71.
See the jsfiddle for a basic example

https://jsfiddle.net/vmsqug94/

**Comment by Akryum** [comment]
I can't reproduce, even in your jsfiddle.

**Comment by albertodeago** [comment]
Looks like I can't reproce it either now. No idea how's that was happening. I'm going to close this. Thanks
