### ISSUE TITLE
how to increase the tooltip width?

### ISSUE THREAD

**Issue by hyoo** [Akryum/v-tooltip#175]
It seems like the tooltip width is fixed to 200px. When I try to resize the width with a custom css, the position gets screwed. Is there any way to do this?

**Comment by PrimozRome** [comment]
I would like to know this too...

**Comment by daopapp** [comment]
Hi, just put this on your custom scss:
.tooltip-inner {
      max-width: 300px !important;

**Comment by PrimozRome** [comment]
@daopapp that does not work unfortunately. Here is the result.

This is the normal result, without modifications:

<img width="1076" alt="Screenshot 2019-03-11 at 15 08 20" src="https://user-images.githubusercontent.com/1180467/54129884-8babc880-440f-11e9-827b-69f2863c6051.png">

If I just add this:

```
.tooltip-inner {
    max-width: 600px !important;
}
```

the result is the same.

If I add this:

```
.tooltip-inner {
    max-width: 600px !important;
    width: 600px !important;
}
```

result is:

<img width="726" alt="Screenshot 2019-03-11 at 15 05 55" src="https://user-images.githubusercontent.com/1180467/54129917-9d8d6b80-440f-11e9-91f3-e98ad396325b.png">

So nothing solves the width problem...

**Comment by Akryum** [comment]
No CSS is applied to the tooltips/popover from v-tooltip. Check your own CSS or change the class in the default options since another library like bootstrap may force styles on you. See #190

**Comment by Akryum** [comment]
(I hate bootstrap :joy_cat:)

**Comment by oscarhandsome** [comment]
for vue/nuxt it will be
`.v-popper__inner {
  max-width: 360px !important;
}`

**Comment by JeanvdspuyE8** [comment]
> Hi, just put this on your custom scss: .tooltip-inner { max-width: 300px !important;



> @daopapp that does not work unfortunately. Here is what I get out of it.
> 
> 1. This is the normal result, without modifications:
> 
> <img alt="Screenshot 2019-03-11 at 15 08 20" width="1076" src="https://user-images.githubusercontent.com/1180467/54129884-8babc880-440f-11e9-827b-69f2863c6051.png">
> 
> 2. If I add what you suggested, the result is the same as above:
> 
> ```
> .tooltip-inner {
>     max-width: 600px !important;
> }
> ```
> 
> 3. If I add also width like this:
> 
> ```
> .tooltip-inner {
>     max-width: 600px !important;
>     width: 600px !important;
> }
> ```
> 
> result is:
> 
> <img alt="Screenshot 2019-03-11 at 15 05 55" width="726" src="https://user-images.githubusercontent.com/1180467/54129917-9d8d6b80-440f-11e9-91f3-e98ad396325b.png">
> 
> 4. It styles it okay if I additionally apply this rules...
> 
> ```
> .tooltip {
>     width: 602px !important;
>     min-width: 602px !important;
> }
> ```
> 
> ... but this brings placement issues:
> 
> <img alt="Screenshot 2019-03-11 at 15 13 48" width="1071" src="https://user-images.githubusercontent.com/1180467/54130357-8602b280-4410-11e9-839d-3b47816166ac.png">
> 
> Nothing really helpful...

This sorted out my issues.

.tooltip-inner {
    max-width: 800px !important; //constrained to max width
    width: max-content !important; //uses the content as a guide of default length
    text-align: left;
}
