### ISSUE TITLE
How to pass parameters to asyncMethod?

### ISSUE THREAD

**Issue by H0WARDDD** [Akryum/v-tooltip#176]
I want to use asyncMethod like this:
`<span v-tooltip="{ content: asyncMethod(params), loadingContent: 'Loading...',  }">`
But it seems that the asyncMethod will execute at once, I could only write it like this:
`<span v-tooltip="{ content: asyncMethod, loadingContent: 'Loading...',  }">`

**Comment by Akryum** [comment]
Use `content: () => asyncMethod(params)`.
