### ISSUE TITLE
v-popover may lead memory leak

### ISSUE THREAD

**Issue by Alecyrus** [Akryum/v-tooltip#177]
When I use v-popover in my component, if I switch the component by changing the routes page frequently. I found the number  of v-popover component instance could increase with the routes changing.  Once I comment all v-popover code, the memory usage falls down.  Recently I realize the memory management is very important because the memory leak of my APP, so i start to assess the potential memory leak risk of  every 3-rd party component I used. 

The following is timeline analysis. Add the v-popover component &  Remove v-popover component
![image](https://user-images.githubusercontent.com/13865581/50945711-efc61500-14d0-11e9-903c-e7b5de6c5623.png)

**Comment by Alecyrus** [comment]
My mistake...

**Comment by zx-81-16k** [comment]
Hi, can you explain what was a mistake ?
