### ISSUE TITLE
A callback for when the tooltip is showing

### ISSUE THREAD

**Issue by luke-peary** [Akryum/v-tooltip#178]
I need to add Google Analytics to our form interactions, including tooltips.

Is there a callback available for 'on show'? I'm currently using the tooltip as a directive rather than a component.

Thanks in advance.

**Comment by PrimozRome** [comment]
See the Events section in the docs here 
https://github.com/Akryum/v-tooltip#popover-component-reference

There are `@show` and `@hide`events which you can use!
