### ISSUE TITLE
How to set width of v-popup component?

### ISSUE THREAD

**Issue by PrimozRome** [Akryum/v-tooltip#179]
Is it even possible or is limited to those 200px or so?

**Comment by PrimozRome** [comment]
Anyone?

**Comment by DBLaci** [comment]
Duplicate of: https://github.com/Akryum/v-tooltip/issues/175

max-width on inner solved the problem for mi, but not for every size. 500px worked, but 800px started flickering the tooltip, so it's not perfect.

**Comment by Akryum** [comment]
Duplicate of #175
