### ISSUE TITLE
Error: Tooltip to attach to at SuperTooltip

### ISSUE THREAD

**Issue by jbharatrhodes** [Akryum/v-tooltip#18]
Hi,
I had used the tooltip and it was fine until today. When i was trying to access the website, I got the following error. Do you think its because of the change in library or any other issues?

 
vue.min.js:7 Error: Tooltip Error: You must provide a target for Tooltip to attach to at SuperTooltip.Tooltip (unpkg.com/tether-tooltip@1.2.0:44) at new SuperTooltip (unpkg.com/v-tooltip@2.0.0-beta.4:1) at createTooltip (unpkg.com/v-tooltip@2.0.0-beta.4:1) at update (unpkg.com/v-tooltip@2.0.0-beta.4:1) at Yt (vue.min.js:6) at Wt (vue.min.js:6) at Array.qt (vue.min.js:6) at b (vue.min.js:6) at _ (vue.min.js:6) at b (vue.min.js:6) 

Cheers

**Comment by jbharatrhodes** [comment]
downgraded to version 1.6 and its working now

**Comment by Akryum** [comment]
Reopening because may be an issue with the new version.

**Comment by Akryum** [comment]
If you still have the issue with the latest release, please let me know in a comment.
