### ISSUE TITLE
Load and render v-popup component only when needed?

### ISSUE THREAD

**Issue by PrimozRome** [Akryum/v-tooltip#180]
Is it possible to load/render `v-popup` component only when needed? For example manually when some element is clicked.

Why like that? I have a table where some cells have elements that can trigger v-popup. Now using v-popup like this:

```
<td>
  <v-popover>
    <template slot="popover">
      <MyCustomPopupComponent />
    </template>
  </v-popover>
</td>
```

will load and pre-render `v-popup` component (and it's child components) in advance for every table cell where I need it. It is a waste of resources. Why preloading every popup and it's content in-front, if you only need it when "trigger" element is clicked?

![screenshot 2019-01-12 at 10 32 49](https://user-images.githubusercontent.com/1180467/51072663-5a5b8a00-1664-11e9-9c1b-72751b82e458.png)

I wanted to do something like this:

```
<template>
  <button @click="togglePopup">Popup trigger</button>

  <v-popover 
    v-if="popupOpen"
    :show="popupOpen"
    trigger="manual">
    <template slot="popover">
      <MyCustomPopupComponent />
    </template>
  </v-popover>
</template>

methods: {
  togglePopup () {
    this.popupOpen = ! this.popupOpen
  }
}
```

This would not work. Any ideas?

**Comment by xeboo** [comment]
Hi, what was your solution here?

**Comment by jomko** [comment]
> Hi, what was your solution here?

Solution was simple as it. Don't trigger 'show', but 'open':
`<template>
  <button @click="togglePopup">Popup trigger</button>

  <v-popover 
    v-if="popupOpen"
    :open="popupOpen"
    trigger="manual">
    <template slot="popover">
      <MyCustomPopupComponent />
    </template>
  </v-popover>
</template>

methods: {
  togglePopup () {
    this.popupOpen = ! this.popupOpen
  }
}`
