### ISSUE TITLE
External trigger element

### ISSUE THREAD

**Issue by PrimozRome** [Akryum/v-tooltip#182]
Can I have external triggered element, something like this?

```
<button>Click me</button>
<v-popover>
  <MyAwesomeComponent slot="popover"/>
</v-popover>
```

I am loading the VPopover component synchronously so that the component is loaded only when I need it. This use case works something like this, but since the **trigger element** is inside the component it's also not visible. 

```
<v-popover v-if="popoverVisible">
  <button>Click me</button>
  <MyAwesomeComponent slot="popover"/>
</v-popover>
```

How difficult would it be to implement an external trigger element?

**Comment by Akryum** [comment]
Use a boolean data and the manual mode (see the docs).
