### ISSUE TITLE
Remove title-attribut on hover

### ISSUE THREAD

**Issue by kaiserkiwi** [Akryum/v-tooltip#183]
Hi there,

it would be awesome if we could an option to dynamically remove the title-Attribut of an Element, when v-tooltip is attached to it. For accessibility reasons we keep the title in our sites but enhance the visuals with v-tooltip. It would be nice if we could globally "deactivate" the title, for elements that are v-tooltip enhanced.

Best regards,
Marco from Germany

**Comment by dweldon** [comment]
Related question: #191 
@kaiserkiwi Could you use `aria-label` instead of `title`? In my case, I have a "play" button that I could add `aria-label="play"` to, however that plus the tooltip with the same text will read as "play button play" which seems a bit silly.

**Comment by jcupps** [comment]
Would it be possible to add an option to disable this behavior? I have a use case in which it's desired to retain the title.
