### ISSUE TITLE
Disable console warnings about modifiers

### ISSUE THREAD

**Issue by HerrEisenheim** [Akryum/v-tooltip#187]
In google chrome devtools@console, I see the following warnings whenever I hover/click on a v-tooltip element:

```
`keepTogether` modifier is required by `arrow` modifier in order to work, be sure to include it before `arrow`!
preventOverflow` modifier is required by `hide` modifier in order to work, be sure to include it before `hide`!
```

How do I disable them? I tried setting the global popper modifiers to none like this:

```
VTooltip.options.defaultPopperOptions = {
    modifiers: []
};

```

...but no luck! How can I get rid of them?

**Comment by HerrEisenheim** [comment]
I have updated the `defaultPopperOptions` to the following:

```
VTooltip.options.defaultPopperOptions = {
    modifiers: {
      preventOverflow: {
        enabled: false
      },
      hide: {
        enabled: false
      },
      keepTogether: {
        enabled: false
      },
      arrow: {
        enabled: false
      },
    }
};
```

The warning about `preventOverflow` modifier is gone, but the warning about `keepTogether` still remains.

**Comment by Akryum** [comment]
This is related to popper.js, not v-tooltip itself.

**Comment by p-m-jakubowski** [comment]
Actually the error is caused by `v-tooltip`. 

https://github.com/Akryum/v-tooltip/blob/master/src/lib/tooltip.js#L364-L369

`_ensureShow` method overrides `arrow` modifier specified in `defaultPopperOptions` hence removing `arrow.enabled: false`
