### ISSUE TITLE
Manual option, but no details on how to trigger?

### ISSUE THREAD

**Issue by jaybeecave** [Akryum/v-tooltip#19]

**Comment by Akryum** [comment]
The target element will have a `_tooltip` property referencing the Popper tooltip object, so with refs you could do something like this:

```javascript
this.$refs.myButton._tooltip.open()
```

**Comment by jacobmischka** [comment]
In case anyone comes across this like I did, the current methods on the `_tooltip` object are `show()` and `hide()`.

**Comment by bengirl** [comment]
在么用？你能做一个例子吗？ v-tooltip.top-center="{ content: errors.first('email'),trigger:'manual' }"

**Comment by jacobmischka** [comment]
Here's one of my full components, the important bits are `tooltipOptions` and the `loading` watcher.

```vue
<template>
	<span ref="loadingContainer" v-tooltip="tooltipOptions">
		<button v-if="loading" class="btn" :class="loadingClass" title="Loading" disabled>
			<svg-icon src="/img/ring.svg" />
		</button>
		<slot v-else></slot>
	</span>
</template>

<script>
import { VTooltip } from 'v-tooltip';

import SvgIcon from './SvgIcon.vue';

export default {
	directives: {
		tooltip: VTooltip
	},
	props: {
		loading: {
			type: Boolean,
			default: false
		},
		loadingClass: {
			type: [String, Object],
			required: false
		},
		successful: {
			type: Boolean,
			default: false
		},
		tooltip: {
			type: String,
			default: 'Done!'
		},
		tooltipTimeout: {
			type: Number,
			default: 3000
		}
	},

	computed: {
		tooltipOptions() {
			return {
				content: this.tooltip,
				trigger: 'manual'
			};
		}
	},

	watch: {
		loading(loading, oldLoading) {
			if (!loading && oldLoading && this.successful) {
				this.$refs.loadingContainer._tooltip.show();
				window.setTimeout(() => {
					this.$refs.loadingContainer._tooltip.hide();
				}, this.tooltipTimeout);
			}
		}
	},

	components: {
		SvgIcon
	}
};
</script>
```

**Comment by bengirl** [comment]
When you lose focus, open tooltip？
`<template>
<div>
  <div class="simple-root">
    <input :style="{outline:'none'}" v-validate.initial="'required|email'" @blur="validate" :class="{'form-control': true, 'is-danger': errors.has('email') }" type="text" name="email" placeholder="Email" />
    <div v-show="errors.has('email')" class="help is-danger">{{ errors.first('email') }}</div>
  </div>
  <div style="margin-top:20px">
    
    

    <div style="width:250px; margin:0 auto;">
      <el-input v-tooltip.top-start="{ content: errors.first('alpha_dash'),trigger:'manual' }"
                ref="myButton"
                v-validate="'required|alpha_dash'"
                data-vv-delay="500"
                data-vv-value-path="innerValue"
                data-vv-name="alpha_dash"
                :has-error="errors.has('alpha_dash')"
                :class="{'input-init': true, 'is-danger': errors.has('alpha_dash') }"
                placeholder="必填"
                @change="changeHandle"
                @blur="validate"
                :style="{outline:'none'}">
      </el-input>
      <p style=" margin-top:60px;"></p>
      <el-input v-tooltip.top-start="{ content: errors.first('alpha'),trigger:'click' }" refs="myButton" v-validate="'required|alpha'" data-vv-delay="500" data-vv-value-path="innerValue" data-vv-name="alpha" :has-error="errors.has('alpha')"
        :class="{'input-init': true, 'is-danger': errors.has('alpha') }" placeholder="必填" @change="changeHandle" :style="{outline:'none'}">
      </el-input>
    </div>
    <div style="width:250px; margin:0 auto;">
      <button @click='subFormData'>提交</button>
    </div>
  </div>
</div>
</template>

<script>
export default {
  name: 'myTest',
  data () {
    return {
      msg: 'This is a button'
    }
  },
  methods: {
    validate (val, val2, val3) {
      debugger
      this.$refs.myButton.$refs._tooltip.show()
      // debugger
      // alert(555555555555)
    },
    changeHandle (val) {
      // debugger
      this.$refs.myButton._tooltip.show()
    },
    click1 () {
      debugger
      this.show()
    },
    subFormData () {
      this.$validator.validateAll().then(result => {
        if (result) {
          // eslint-disable-next-line
          alert('From Submitted!')
          return
        }
        alert('Correct them errors!')
      })
      alert(2222)
    }
  }
}
</script>

<style>
.tooltip {
  display: block !important;
  padding: 4px;
  z-index: 10000;
}

.tooltip .tooltip-inner {
  background: #d1d1d1;
  color: red;
  border-radius: 4px;
  padding: 10px;
  font-size: 12px;
}

.tooltip .tooltip-arrow {
  display: block;
  border-top-color: #d1d1d1;
  left: 10px;
  border-width: 6px;
  position: absolute;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
}

.tooltip .tooltip-arrow::after {
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  content: " ";
  border-width: 5px;
}

.tooltip[aria-hidden='true'] {
  visibility: hidden;
  opacity: 0;
  transition: opacity .15s, visibility .15s;
}

.tooltip[aria-hidden='false'] {
  visibility: visible;
  opacity: 1;
  transition: opacity .15s;
}

.input-init {
  border: 1px solid #fff;
}

.is-danger {
  border: 1px solid red;
  color: red;
}
</style>
`
@Uncaught TypeError: Cannot read property 'show' of undefined

**Comment by jacobmischka** [comment]
I think you should remove the second `$refs` from your calls, so this instead: `this.$refs.myButton._tooltip.show()`

**Comment by stefli** [comment]
Check the dom tree to find the element who has_tooltip attribute, then use the dom path to invoke the show() or hide() function.
Something likes what jacobmischka mentioned.

**Comment by Akryum** [comment]
I think we can close this now.

**Comment by mokkabonna** [comment]
Shouldn't options support `open` when using directive? Just like for component. Using the _tooltip.show() function seems a bit dirty to me.

**Comment by edDimensi** [comment]
@Akryum really, add plz open options for tooltip. It's look dirty using $refs for manipulate tooltips.

**Comment by RavenXce** [comment]
Having to do this is sad:

```
watch: {
      leftTipVisible(visible) {
        visible ? this.$refs.leftTip._tooltip.show() : this.$refs.leftTip._tooltip.hide();
      },
      rightTipVisible(visible) {
        visible ? this.$refs.rightTip._tooltip.show() : this.$refs.rightTip._tooltip.hide();
      },
      startTipVisible(visible) {
        visible ? this.$refs.startTip._tooltip.show() : this.$refs.startTip._tooltip.hide();
      },
      endTipVisible(visible) {
        visible ? this.$refs.endTip._tooltip.show() : this.$refs.endTip._tooltip.hide();
      },
      paymentTipVisible(visible) {
        visible ? this.$refs.paymentTip._tooltip.show() : this.$refs.paymentTip._tooltip.hide();
      },
      cutTipVisible(visible) {
        visible ? this.$refs.cutTip._tooltip.show() : this.$refs.cutTip._tooltip.hide();
      }
}
```
Will you be adding a prop or are accepting a PR for this? It doesn't seem hard to do.

**Comment by kgrosvenor** [comment]
Any news on this, i'm hitting the same barrier?

**Comment by edDimensi** [comment]
@Akryum reopen this, plz.

**Comment by emmanuel-franc** [comment]
indeed, it would be great
