### ISSUE TITLE
Headache, not issue : Opacity is 0 due to class name collision.

### ISSUE THREAD

**Issue by rwdim** [Akryum/v-tooltip#190]
Confirmed that dom nodes are present and correct at end of body, but opacity gets stuck at 0.

Issue is class-name collision with another *very popular* templating package that uses tooltip class generously.

>Use of generic class names like "tooltip" when users employ templates 
> or scss/sass from imported packages causes collisions.  
> The classnames for this should be vtooltip- or better.  

Temporary fix: (based on code from another related issue):

```
    .tooltip[aria-hidden="false"] {
        opacity: 1;
        transition: .2s ease all;
    }
```

**Comment by Akryum** [comment]
Yeah I have planned to change the default classes in the next Major release (it would be a breaking change).

**Comment by Akryum** [comment]
In the meantime you can also change the class used in the default template: https://github.com/Akryum/v-tooltip#global-options
