### ISSUE TITLE
Tooltip starts blinking with container "overflow: auto" css

### ISSUE THREAD

**Issue by rreckonerr** [Akryum/v-tooltip#192]
I have a sidebar which I recently decided to make independently scrollable. When I set `overflow: auto;` to the `sidebar-wrapper` class or `<aside>` html element, v-tooltip with `placement: right` starts to blink and it's almost impossible to see what's in the popover. 

When I switch placement of the popover to default blinking goes away. I've tried to disable all tooltip styles, but it didn't help.

What's going on? How can I set the overflow property without having this weird behavior?

**Comment by pmochine** [comment]
I have the same problem, it was mentioned that you can fix it with this option, but it didn't work for me, maybe it works for you.

```
popperOptions: {
    modifiers: {
      preventOverflow: {
        escapeWithReference: true
      }    
    }
  }
```

**Comment by rreckonerr** [comment]
@pmochine that's incredible! It worked fine for me, thank you!

**Comment by ReTWi** [comment]
Better use:
```
popperOptions: {
  modifiers: {
    preventOverflow: {
      boundariesElement: 'window'
    }
  }
}
```

**Comment by cainaf** [comment]
this is what worked for me:

```js
import VTooltip from 'v-tooltip';
import Vue from 'vue';

Vue.use(VTooltip, {
  defaultBoundariesElement: 'window',
});
```

**Comment by TheMangoTrain** [comment]
The fix worked for me. For reference, this is my usage:

```
<v-popover :popperOptions="{ modifiers: { preventOverflow: { boundariesElement: 'window' } } }">
    <slot name="button" />
    <template slot="popover">
        <slot name="content" @passEvent="passEvent($event)" />
    </template>
</v-popover>
```
