### ISSUE TITLE
Example don't work for me

### ISSUE THREAD

**Issue by pawkus** [Akryum/v-tooltip#20]
version 2.0.0.beta.4, version 2.0.0.beta.3, version 2.0.0.beta.2, version 2.0.0.beta.1

In my code, example below do not work.
import Vue from 'vue'
import { VTooltip } from 'v-tooltip'
Vue.directive('my-tooltip', VTooltip)

I do not see anything and I have no errors.

but this example do job perfekt
Vue.directive('focus', {
  inserted: function (el) {
    el.focus()
  }
})

**Comment by Akryum** [comment]
If you still have the issue with the latest release, please let me know in a comment.
