### ISSUE TITLE
different triggers for open and close

### ISSUE THREAD

**Issue by albertodeago** [Akryum/v-tooltip#207]
Hello, thanks in advance for the beautiful work done, I really like the library.

I wanted to create a tooltip that opens at click and closes at mouseleave.
I tried by using 

```javascript
trigger: "manual"
@click="showTooltip=true" 
@mouselease="showTooltip=false"
```

This works but this way the default animation (fade) is not there anymore, the tooltip open and closes immediately and I don't want this to happen.
I can make a work around by switching the 'opacity' property of the element inside a callback like

```javascript
@mouseleave="hideTooltip"
```

```javascript
hideTooltip: function() {
  const tooltipEl = this.$el.querySelector(".th-simple-tooltip");
  if (tooltipEl) {
    tooltipEl.style.opacity = 0;
    setTimeout(() => {
    this.showTooltipWarning = false;
   tooltipEl.style.opacity = 1;
  }, 150);
}
```

This restores also the opacity but it's pretty ugly imho.

Am I missing something? Is there a way to make this more easily?
Because I think is pretty common to need a tooltip that open with an event and closes with a different one.

**Comment by Akryum** [comment]
It's already possible, see [Manual triggering](https://github.com/Akryum/v-tooltip#manual-trigger-example).

**Comment by albertodeago** [comment]
Looks like you are right because I'm not able to reproduce my problem in a simple jsfiddle like this (https://jsfiddle.net/j4gyvepu/1/).
In my app I'm losing the opacity transition somehow but I'll figure it out.

Thanks for everything
