### ISSUE TITLE
Update lodash.merge dependency

### ISSUE THREAD

**Issue by jamesmacwhite** [Akryum/v-tooltip#209]
A low severity vulnerability has been identified in lodash.merge < 4.17.11.

https://app.snyk.io/vuln/SNYK-JS-LODASHMERGE-173732

Would it be possible to update the dependency?

**Comment by jamesmacwhite** [comment]
https://github.com/Akryum/v-tooltip/pull/203

**Comment by Akryum** [comment]
Done

**Comment by antoniopaisfernandes** [comment]
Can the package.json be updated also?

**Comment by Akryum** [comment]
It's up-to-date: https://www.npmjs.com/package/lodash.merge

**Comment by antoniopaisfernandes** [comment]
The issue has been referred in https://github.com/lodash/lodash/issues/4171.

Still, the vuln https://snyk.io/vuln/SNYK-JS-LODASHMERGE-173733 was published in 14 Feb, 2018 and no fix was done in a new released version.

Would you consider replacing lodash.merge with the primary lodash package and fetch only the needed module?

**Comment by antoniopaisfernandes** [comment]
Thank you so much!
