### ISSUE TITLE
Uncaught TypeError: Super expression must either be null or a function, not object

### ISSUE THREAD

**Issue by azhard4int** [Akryum/v-tooltip#21]
Hi,

Getting this error "Uncaught TypeError: Super expression must either be null or a function, not object" when using the latest release version v2.0.0-beta.2.

Reverting down to the 1.1.2 works fine.

**Comment by hazzo** [comment]
I can't get it work either in 1.1.2. I think that there is an incompatibility with another recently updated packages.

**Comment by Akryum** [comment]
Is this still the case with the latest version?

**Comment by seniorcreative** [comment]
I am having this issue also with latest version.

**Comment by hazzo** [comment]
Still same error.

**Comment by brenzy** [comment]
I think this may happen if you have both the tether tooltips and the popper tooltips installed in the node_modules directory.  You may want to try cleaning out the node_modules directory and running `npm install` again.  docs/test.html is including tether tooltips (and should be updated) and exhibits similar behaviour.

**Comment by Akryum** [comment]
If you still have the issue with the latest release, please let me know in a comment.
