### ISSUE TITLE
Moving the mouse around quickly makes popovers stay open

### ISSUE THREAD

**Issue by johnRivs** [Akryum/v-tooltip#220]
How do I deal with this?
![](https://i.imgur.com/h9SOtrx.gif)

**Comment by rootman** [comment]
I experience the same behavior, a fix is really appreciated, I will look into it as well.

**Comment by teuneboon** [comment]
Have the same issue. It seems to be easier to reproduce if you do some async stuff with the tooltip, but not completely impossible if you don't.

**Comment by kabalage** [comment]
I'm also having trouble with this problem. Delaying the tooltip makes it occure less frequently, but still very annoying. `:delay="{ show: 50, hide: 0 }"`

**Comment by rootman** [comment]
I feel like I have found and solved the issue, it was due to requestAnimationFrame.

**Comment by pmochine** [comment]
@rootman I hope this works and will be merged 🙈The bug is quite annyoing^^

**Comment by Akryum** [comment]
Closed in #228
