### ISSUE TITLE
tooltip doesn't showed up

### ISSUE THREAD

**Issue by alditahir08** [Akryum/v-tooltip#222]
I have followed the documentation and copy the style to the scoped css in my component.
Somehow the button managed to changed class into "v-tooltip open" when i hover and it generate a unique aria-describedby, but the div class="tooltip" itself didn't showed up like the one i inspect in this fiddle https://jsfiddle.net/Akryum/tsjco74e/ when you hover on it.

I wonder what is wrong, it should have just works well and easy. And btw, is using bootstrap still causing trouble with the 'tooltip' class ? ? 
i'm using the 
v-tooltip 2.0.0-rc.33,
Vue 2.5.17,
bootstrap,
and runs on webpack with laravel.

**Comment by AlexTheRegent** [comment]
Seems like bootstrap do cause troubles with 'tooltip' class.

I've managed to make it work with basic example by making two steps:
1. Override template, arrowSelector and innerSelector from `tooltip` to `tooltip-vue`:
`button.tooltip-target(v-tooltip="{content: 'You have new messages.', template: '<div class=\"tooltip-vue\" role=\"tooltip\"><div class=\"tooltip-vue-arrow\"></div><div class=\"tooltip-vue-inner\"></div></div>', arrowSelector: '.tooltip-vue-arrow, .tooltip-vue__arrow', innerSelector: '.tooltip-vue-inner, .tooltip-vue__inner'}") popup`
2. Copy whole style css https://github.com/Akryum/v-tooltip#css and find-replace 
`.tooltip` to `.tooltip-vue`.

I think this should work for advanced examples too.

**Comment by arthursb2016** [comment]
@AlexTheRegent It's not clear for me what I should do on step one, can you give more details?

**Comment by Akryum** [comment]
See [Global Options](https://github.com/Akryum/v-tooltip#global-options) to change the CSS class in the default template.

**Comment by alditahir08** [comment]
> Seems like bootstrap do cause troubles with 'tooltip' class.
> 
> I've managed to make it work with basic example by making two steps:
> 
> 1. Override template, arrowSelector and innerSelector from `tooltip` to `tooltip-vue`:
>    `button.tooltip-target(v-tooltip="{content: 'You have new messages.', template: '<div class=\"tooltip-vue\" role=\"tooltip\"><div class=\"tooltip-vue-arrow\"></div><div class=\"tooltip-vue-inner\"></div></div>', arrowSelector: '.tooltip-vue-arrow, .tooltip-vue__arrow', innerSelector: '.tooltip-vue-inner, .tooltip-vue__inner'}") popup`
> 2. Copy whole style css https://github.com/Akryum/v-tooltip#css and find-replace
>    `.tooltip` to `.tooltip-vue`.
> 
> I think this should work for advanced examples too.

For everyone that still wondering how to solve the tooltip doesn't showed up because of the bootstrap class simply just do this :

step 1 : 
import VueTooltip from 'v-tooltip';
Vue.use(VueTooltip);
VueTooltip.options.defaultTemplate = '<div class="tooltip-vue" role="tooltip"><div class="tooltip-vue-arrow"></div><div class="tooltip-vue-inner"></div></div>';
VueTooltip.options.defaultArrowSelector = '.tooltip-vue-arrow, .tooltip-vue__arrow';
VueTooltip.options.defaultInnerSelector = '.tooltip-vue-inner, .tooltip-vue__inner';

step 2 just like @AlexTheRegent said, copy whole style css and find-replace `.tooltip `to .tooltip-vue
