### ISSUE TITLE
Issues on mobile

### ISSUE THREAD

**Issue by andreimoment** [Akryum/v-tooltip#23]
Tooltips appear on tapping the element, but do not disappear when the finger is removed.

Also, on a narrow screen, tooltips ignore the positioning (.right tooltips appear centered).

**Comment by Akryum** [comment]
> Tooltips appear on tapping the element, but do not disappear when the finger is removed.

Well, that's the way hover events work on mobile browsers. Maybe open an issue on popper repo.

> Also, on a narrow screen, tooltips ignore the positioning (.right tooltips appear centered).

If the tooltip decides there is not enough space, it can change the position.

**Comment by yuri-karkh** [comment]
Confirm such behavior. On mobile on tap tooltip opens and not hides if click outside.

**Comment by iMomen** [comment]
Any updated about this?

**Comment by andreimoment** [comment]
I ended up not using this because it's incompatible with mobile.

**Comment by yuri-karkh** [comment]
As a possible turnaround guys: when on mobile u set display:none to the tooltip and attach click event handler for its parent element, then just toggle it from display none to display block on click.

```
<button class="button text feed-article__people" v-tooltip.bottom-center="bookmarkedPeople"
				v-if="isDesktopView">
				<i class="icon-bookmarked feed-article__peopleIcon"></i> {{ bookmarkedByPeople }}
				bookmark<span v-if="bookmarkedByPeople !== 1">s</span>
			</button>
			<button class="button text feed-article__people" @click="toggleBookmarkedByState( $event )" v-else>
				<i class="icon-bookmarked feed-article__peopleIcon"></i> {{ bookmarkedByPeople }}
				bookmark<span v-if="bookmarkedByPeople !== 1">s</span>
				<div class="feed-article__peopleList" v-html="bookmarkedPeople"></div>
			</button>
```

```
+element( 'people' )
		display: inline-block
		position: relative

		+element( 'peopleList', $component )
			display: none

		+modifier( 'open' )
			+element( 'peopleList', $component )
				display: block
```

**Comment by Akryum** [comment]
I may have to add touch events to have a better behavior than the browser default on touchscreens.
