### ISSUE TITLE
Blurry text on browser zoom

### ISSUE THREAD

**Issue by kaiserkiwi** [Akryum/v-tooltip#233]
Hi,
I just noticed that the text on any tooltip gets blurry if I use the integrated zoom in any browser. I first thought it was some mistake on my end, but even on your demo page you can see this problem. (See screenshot, Browserzoom 90%)

Any idea how to fix this?

![image](https://user-images.githubusercontent.com/8428551/55793707-da5a8a00-5ac3-11e9-8124-3593f0cc6c88.png)

**Comment by Akryum** [comment]
I guess it's because popper.js uses CSS transform to efficiently move the tooltip on the page.

**Comment by kaiserkiwi** [comment]
Yeah I saw this. If I change it to CSS-Position values (top, right, left, bottom), then it's fine. The question is: Why is it using this? Seems pretty pointless to me in this case.

**Comment by kaiserkiwi** [comment]
Ok. I asked the popper.js people in this Issue: https://github.com/FezVrasta/popper.js/issues/779

They said, I just have to disable `gpuAcceleration`. Sadly the following line changes nothing: 
`VTooltip.options.defaultPopperOptions.gpuAcceleration = false;`

Other options are working fine. Is there any way to access this option in v-tooltip?

**Comment by Akryum** [comment]
Everything is working correctly, but the Popper.js documentation could be improved... :smile_cat: 

```js
VTooltip.options.defaultPopperOptions = {
  modifiers: {
    computeStyle: {
      gpuAcceleration: false,
    },
  },
}
```

**Comment by kaiserkiwi** [comment]
I just saw, that the problem is only solved for Tooltips. Popovers are not affected.

I import v-tooltip like this, what did I do wrong?

```
import VTooltip from 'v-tooltip';

VTooltip.options.defaultPopperOptions = {
	modifiers: {
		computeStyle: {
			gpuAcceleration: false,
		},
	},
};

Vue.use(VTooltip);
```

**Comment by Mortymus** [comment]
For anybody still interested, here is the correct setting for popovers:
```
import VTooltip from 'v-tooltip';

VTooltip.options.popover.defaultPopperOptions = {
    modifiers: {
        computeStyle: {
            gpuAcceleration: false,
        },
    },
};
```

**Comment by badalsaibo** [comment]
```js
import FloatingVue, { Dropdown } from 'floating-vue';
import 'floating-vue/dist/style.css';

FloatingVue.options.dropdown = {
  modifiers: {
    computeStyle: {
      gpuAcceleration: false,
    },
  },
};
```
