### ISSUE TITLE
Error importing VTooltip during production webpack build with UglifyJS

### ISSUE THREAD

**Issue by nlitwin** [Akryum/v-tooltip#239]
I recently ran into an error that seems like it's coming from this library. When running my production webpack build, I get the following error:
```
ERROR in vendors-c487e72a0905278b058b.min.js from UglifyJs
Unexpected token: keyword «const» [vendors-c487e72a0905278b058b.min.js:134515,0]
```

When I investigated this error and line, it led me to the code imported from `dist/v-tooltip.umd.js`

```js
// dist/v-tooltip.umd.js

// ... other code

const __vue_script__ = script;

// ... other code

/* style */
const __vue_inject_styles__ = undefined;
/* scoped */
const __vue_scope_id__ = undefined;
/* module identifier */
const __vue_module_identifier__ = undefined;
/* functional template */
const __vue_is_functional_template__ = false;
```

In my Vue code, I'm simply importing the library with these lines:
```js
import VTooltip from "v-tooltip"
Vue.use(VTooltip)
```

It looks like these `const`s were added only a day ago in https://github.com/Akryum/v-tooltip/commit/19cd67b43b9736d435dce28ddaad074e29b00a25 to `dist/v-tooltip.umd.js`

Since it's common practice to ignore transpiling code imported from `node_modules` (because they should be transpiled already), I think these `const`s need to be removed from the `dist/v-tooltip.umd.js` file.

Let me know if you have any questions or if I can provide any more information.
Thanks!

**Comment by scniro** [comment]
this broke my app entirely...

**Comment by scniro** [comment]
reverting back to `"v-tooltip": "2.0.0-rc.33"` "fixed" it

**Comment by bissolli** [comment]
Same issue here.

**Comment by overallduka** [comment]
I'm having yet the same issue with v2.0.3. 

Reverted back to 2.0.0-rc.33 by now.

**Comment by quannt** [comment]
Still happening to me on v2.0.3.

**Comment by ElliotPsyIT** [comment]
Exact same error as @overallduka on v2.0.3

**Comment by jandobrowolski** [comment]
@overallduka set dependency in package.json to "2.0.0-rc.33", NOT "^2.0.0-rc.33" or "~2.0.0-rc.33". There is a "let" command on 2.0.3 version, which makes it ES6, hence the error. You can use anything up to 2.0.2.
