### ISSUE TITLE
IE Compatibility issue 

### ISSUE THREAD

**Issue by lgullestrup** [Akryum/v-tooltip#24]
Internet Explorer (Edge and 10) get an error: Object doesn't support property or method 'assign'

**Comment by koronowicz** [comment]
https://stackoverflow.com/a/39021339 get you around this get u around this problem, but another error inside v-tooltip lib occurred

**Comment by EyePulp** [comment]
Adding `babel-polyfill` is a solution, but it adds a lot of code bloat for the benefit.  I'd like to figure out whether it's `tooltip.js` or `v-tooltip` that's using the methods that are breaking IE.  

It would be great to avoid having to special-case for IE and just have it all fixed in my build step (via babel and without additional clientside imports) , but I'm not sure how to diagnose that.

**Comment by Akryum** [comment]
You can [polyfill](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Polyfill) this standard JavaScript method for very old browsers.

**Comment by EyePulp** [comment]
Hey @Akryum - a single polyfill isn't sufficient.  Here's the solution I'm using for webpack with the minimal amount of polyfills:
  - First add the [core-js](https://github.com/zloirock/core-js) package, which are the polyfills used by `babel-polyfill`  -- `npm install core-js --save`
  - then in your code -- `app.js` for example: 
```javascript
// polyfills needed for tooltip in IE.
import 'core-js/fn/object/assign';
import 'core-js/fn/get-iterator';
import 'core-js/fn/symbol';
import VTooltip from 'v-tooltip'
Vue.use(VTooltip);
```

The problem, which I didn't understand, is that babel can only transpile syntax, but it can't solve for missing methods (which is what the polyfills are for).  For example, if @Akryum replaced calls to Object.assign() with the [spread operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_operator), babel would detect and transpile that to es5.   There are differences between the spread operator and Object.assign, so maybe it's not a fix in this particular case.

Thanks for the work on this module @Akryum, I appreciate it! :)
