### ISSUE TITLE
TypeError: Cannot assign to read only property 'className' of object '#<SVGSVGElement>'

### ISSUE THREAD

**Issue by tw00** [Akryum/v-tooltip#246]
When building for production, I get the following error whenever a v-tooltip directive is used on a svg element (e.g. vue-font-awesome):

```
TypeError: Cannot assign to read only property 'className' of object '#<SVGSVGElement>'
   at p (v-tooltip.esm.js:146)
```

Recently this line was introduced, which apparently does not resolve to ```true``` on SVGSVGElement. 

https://github.com/Akryum/v-tooltip/blob/4a02b0fe16007a920e7c7837314885779100aa5a/src/utils.js#L33

From my understanding this is because SVGSVGElement does not have a ```prototype``` property.

```
var svg = document.createElementNS('http://www.w3.org/2000/svg','svg');
svg.prototype
>> undefined
```
(Tested in Chrome 73)

**Comment by afv** [comment]
Hi,

This is happening for me too with `SVGGElement` (corresponds to the `<g>` element)

`directive tooltip bind hook
TypeError: Cannot assign to read only property 'className' of object '#<SVGGElement>'`

**Comment by SirHodlington** [comment]
Hello,

I'm also getting the same error message
`Uncaught TypeError: Cannot assign to read only property 'className' of object '#<SVGSVGElement>'
at removeClasses (v-tooltip.esm.js?e37d:146)
    at Tooltip._hide (v-tooltip.esm.js?e37d:638)
    at eval (v-tooltip.esm.js?e37d:835)`

**Comment by sirjones** [comment]
Hi, also getting same error:
``Cannot assign to read only property 'className' of object '#<SVGSVGElement>'
    at addClasses (v-tooltip.esm.js?54de:114)
    at createTooltip (v-tooltip.esm.js?54de:1019)
    at bind (v-tooltip.esm.js?54de:1055)
    at callHook$1 (vue.esm.js?efeb:6685)
    at _update (vue.esm.js?efeb:6606)
    at Array.updateDirectives (vue.esm.js?efeb:6587)
    at invokeCreateHooks (vue.esm.js?efeb:6074)
    at initComponent (vue.esm.js?efeb:6007)
    at createComponent (vue.esm.js?efeb:5990)
    at createElm (vue.esm.js?efeb:5930)``

**Comment by karolinakuzniewicz** [comment]
When can we expect the fix for this bug? Or perhaps does anyone know some workaround?

**Comment by SirHodlington** [comment]
Not sure if this is any help, but I'm only getting this error since I'm using yarn instead of npm to install my packages.

**Comment by SirHodlington** [comment]
> When can we expect the fix for this bug? Or perhaps does anyone know some workaround?

This workaround worked for me
`yarn remove v-tooltip`
`yarn upgrade v-tooltip@2.0.0-rc.33`
