### ISSUE TITLE
Popover Closes When Content Changes

### ISSUE THREAD

**Issue by hfalucas** [Akryum/v-tooltip#253]
Is there any way to prevent the popover to close when the content changes?

### **How to reproduce** - [jsfiddle](https://jsfiddle.net/hfalucas/cgm7tw1o/64/)
- Click on the button and then click on the button inside the popover (the popover will close).
- Click again on the button to open the popover and now click on the Add button inside of it. This time the popover won't close.

**Comment by Akryum** [comment]
My guess is that the element you clicked on is no longer considered a child of the popover (since it's removed from the DOM) so it thinks you clicked outside of the popover. Try setting `:key="amount"` on the last button to destroy it and create a new one when you click.

**Comment by hfalucas** [comment]
I guess you are right. Setting the same element (e.g `div`) where the `v-if`/`v-else` directives are applied without a `key` seems to solve it, Vue thinks its the same element and doesn't rerender and the popover doesn't seem to think it was clicked outside.

[jsfiddle](https://jsfiddle.net/hfalucas/cgm7tw1o/85/)

There's no problem with this approach right?

Thanks in advance @Akryum :)

**Comment by Akryum** [comment]
Or you can try setting the same key on the buttons (and they should be at the same level in the root tree). But this still feel like a workaround, I wonder if we can somehow still consider the deleted elements as inside the popover.

**Comment by hfalucas** [comment]
I haven't dig in the code of this wrapper much, but that kind of functionality should probably be more related to the popper.js plugin itself no?
