### ISSUE TITLE
In documentation, Naming of directive is wrong. 

### ISSUE THREAD

**Issue by successivesoftware** [Akryum/v-tooltip#26]
I used it as per documentation and include directive like: -
`Vue.directive('my-tooltip', VTooltip);`

and then in the template, I am using it as:
`<button v-tooltip="'You have ' + count + ' new messages.'">
`
and it was not working for me then I used below the line and it works for me
`<button v-my-tooltip="'You have ' + count + ' new messages.'">
`

**Comment by Akryum** [comment]
Thanks!
