### ISSUE TITLE
<script src="https://unpkg.com/v-tooltip"></script>

### ISSUE THREAD

**Issue by jonathanjd** [Akryum/v-tooltip#273]
Not Working

**Comment by Akryum** [comment]
Use `https://unpkg.com/v-tooltip@2`

**Comment by aorczyk** [comment]
Hi, The problem there is also in JSFiddle from "Useful Links" in documentation: https://jsfiddle.net/Akryum/tsjco74e/

**Comment by jonathanjd** [comment]
> Use `https://unpkg.com/v-tooltip@2`

Thx
