### ISSUE TITLE
Was the default className for tooltip changed?

### ISSUE THREAD

**Issue by Akumzy** [Akryum/v-tooltip#280]
My tooltip styles suddenly stopped working after debugging I noticed the class are now `v-popper__popper v-popper--theme-tooltip` instead of `tooltip or tooltip-inner`

**Comment by agri2008** [comment]
you can read here
https://www.npmjs.com/package/v-tooltip#themes

**Comment by Akumzy** [comment]
@agri2008 
Thanks but it has been working that's the point I just switched from Ubuntu to Windows which made me to redownload the modules

I was very surprised at review the tooltip was misbehaving.

**Comment by Akryum** [comment]
It seems I made a mistake publishing 3.0 alpha 7 without the alpha tag.

Le sam. 18 mai 2019 à 07:11, Akuma Isaac Akuma <notifications@github.com> a
écrit :

**Comment by Akryum** [comment]
It should now be fixed :smile_cat: 

![Screenshot from 2019-05-18 12-29-19](https://user-images.githubusercontent.com/2798204/57968305-9e3f0280-7968-11e9-8b3d-c8a301608cf6.png)

**Comment by Akumzy** [comment]
@Akryum Thank you for your great work in Vue community.

**Comment by gadelkareem** [comment]
I used `yarn add v-tooltip` and I ended up with `v-tooltip@3.0.0-alpha.10`

**Comment by Akryum** [comment]
Oops ><

**Comment by Akryum** [comment]
Should be fixed now

**Comment by gadelkareem** [comment]
Thanks!
