### ISSUE TITLE
v-tooltip directive Positioning error

### ISSUE THREAD

**Issue by fengyun2** [Akryum/v-tooltip#287]
### Version:

vue: 2.5.22
v-tooltip: 2.0.2

### Result

[vtooltop-error-rtxum](https://codesandbox.io/s/vtooltop-error-rtxum)

![image](https://user-images.githubusercontent.com/8147202/58409841-8c193e80-80a3-11e9-861f-6ba14f4a1da9.png)

**Comment by Akryum** [comment]
Use:
```js
VTooltip.options.defaultBoundariesElement = 'body';
```
