### ISSUE TITLE
"TypeError: __WEBPACK_IMPORTED_MODULE_0_tether_tooltip___default.a is not a constructor"

### ISSUE THREAD

**Issue by nobuttsseb** [Akryum/v-tooltip#30]
Trying to get it working in the browser. Using v1.1.0. I've utilised the plugin using the v-tooltip directive but is breaks:

"TypeError: __WEBPACK_IMPORTED_MODULE_0_tether_tooltip___default.a is not a constructor"

Constant problems when using browser includes.

**Comment by Akryum** [comment]
The [JSFiddle example](https://jsfiddle.net/Akryum/tsjco74e/) just works though. Make sure you are using the [appropriate distribution file](https://github.com/Akryum/v-tooltip/blob/master/dist/v-tooltip.browser.js) intended for use with the browser.

BNW, on which browser are you testing your code?

**Comment by assuncaojr** [comment]
Hi! The problem appears on safari (mobile and desktop) version 9. In reference object.assign

**Comment by Akryum** [comment]
Do you have a browser console full stack trace of the error?

**Comment by assuncaojr** [comment]
TypeError: undefined is not a function (evaluating 'Object.assign({}, __WEBPACK_IMPORTED_MODULE_0__v_tooltip__["a" /* defaultOptions */], options || {})')
![print](https://user-images.githubusercontent.com/233390/29213743-f7729e4c-7e7a-11e7-8f2e-df99ef5528be.png)

**Comment by Akryum** [comment]
Did you try running the jsfiddle (linked above)? Also, could you try `Object.assign({}, { a: 42 })` in the browsers with the issue?

**Comment by assuncaojr** [comment]
I tested on the mobile safari (jsfiffle on mobile is terrible), also tried to use babel and nothing.
As suggested, Object.assign ({}, {a: 42}) does not work. I think that's the problem

**Comment by Akryum** [comment]
Well, you then need the `Object.assign` polyfill.
