### ISSUE TITLE
Tooltips stopped working on android devices

### ISSUE THREAD

**Issue by AlekJanevski** [Akryum/v-tooltip#316]
Tooltips suddenly stopped working on android devices, I'm using them for quite long and this is the first time that happened something like this. On iOS and desktop/laptop devices is all as it should be but on android devices it's not.

**Comment by lekika** [comment]
I've had the same issue in the last couple of weeks. Couldn't find any workaround, since the tooltips were initially  functional.

**Comment by AlekJanevski** [comment]
Btw. the tooltips are also not working on your demo.

**Comment by shawkivai** [comment]
Is this issue still exists for v-tooltip? 
I got the issue in Android devices but in iphone for any browser it's working properly.

Kindly let us know is it fixed for android or not.
thanks

**Comment by dansiberry** [comment]
I'm still getting this on Android devices. 
Has anyone found a fix ?
