### ISSUE TITLE
Unknown custom element: <v-popover>

### ISSUE THREAD

**Issue by DirKraft4u** [Akryum/v-tooltip#318]
1) I'm install package from npm
2) import VTooltip from 'v-tooltip' 
3) Vue.use(VTooltip)

After these, in my component i use v-popover, but receive this error. I try method with import by {VPopover} from 'v-tooltip and use it by component, but receive same error.

Why?

**Comment by Akryum** [comment]
Apparently my previous fix didn't work, so I tried again it seems ok now :)

**Comment by DirKraft4u** [comment]
"export 'VPopover' was not found in 'v-tooltip'.  Are you sure you updated version?)

**Comment by Akryum** [comment]
Make sure you are on latest (2.0.2): https://www.npmjs.com/package/v-tooltip?activeTab=versions
