### ISSUE TITLE
Installation without npm/webpack?

### ISSUE THREAD

**Issue by oscarjlep** [Akryum/v-tooltip#32]
Hi,

I have generic question on using plugins like v-tooltip. I would like to use v-tooltip source directly as normal external plugin script (imported with script src) without using requirejs/webpack or similar solution. Is it possible to you v-tooltip without building it first?

question 2) If building is mandatory due to dependencies, how can I make such a build that it's globally available for my external vue-scripts which do not rely on building? As far as I have learned, final distributed build.js is on it's own namespace and you cannot call methods within it's space from other external files?

**Comment by Akryum** [comment]
See [browser installation](https://github.com/Akryum/v-tooltip#browser).
