### ISSUE TITLE
Unwanted rerender when dependencies change

### ISSUE THREAD

**Issue by NvdB31** [Akryum/v-tooltip#327]
I'm using a Popover with a component inside that emit change events to the outer component.

I've noticed that something inside this plugin causes the popover to hide whenever a value changes that's being used inside the popover. I can see the following in the events:

- Document click
- Hide
- Update:open
- Dispose

I'm struggling to figure out what I can do to prevent this from happening. I've tried setting the global options regarding hidiing VTooltip but nothing seems to work.

**Comment by Akryum** [comment]
Please provide a minimal runnable reproduction. :pray:
