### ISSUE TITLE
Set classes by placement

### ISSUE THREAD

**Issue by H0WARDDD** [Akryum/v-tooltip#33]
Is that possible to add an option to set classes by placement?

**Comment by Akryum** [comment]
Could you provide an example please?

**Comment by H0WARDDD** [comment]
I use v-tooltip with bootstrap4, they have different classes for different placement to show the arrow. So I expect it like this: 
placementClass: {
  top: 'tooltip-top',
  bottom: 'tooltip-bottom',
  left: 'tooltip-left',
  right: 'tooltip-right'
}

**Comment by Akryum** [comment]
Popper.js adds a `x-palcement` attribute on the tooltip.

```css
.tooltip[x-placement='right'] { }
```

**Comment by justinwinslow** [comment]
Sorry to bump an old thread. Is it possible to similarly add the attribute to the popover root element? It's useful to style the "trigger" based on the position of the popover.
