### ISSUE TITLE
Ambiguous license

### ISSUE THREAD

**Issue by pblumenkamp** [Akryum/v-tooltip#331]
I am summarizing the dependencies of software I wrote, and I noticed that v-tooltip has two licenses at the moment.

The [LICENSE](https://github.com/Akryum/v-tooltip/blob/master/LICENSE) file says MIT but the ['package.json'](https://github.com/Akryum/v-tooltip/blob/master/package.json) ISC. So which is the real license for v-tooltip? MIT, ISC, or both?

**Comment by winterwings** [comment]
iirc, `npm init` writes down ISC as a default license if you skip it, so it is likely an oversight.  
On the other hand, the license file is created manually, so I take it as this package is actually MIT.

In any case, they are functionally similar.
