### ISSUE TITLE
autoHide dont close if trigger click

### ISSUE THREAD

**Issue by brunokunace** [Akryum/v-tooltip#332]
Hi everyone,

i try to autohide tooltip with directive, on click outside of my button, but dont work.
if popover, works fine.

on example have the two tries.

```
<button
  v-tooltip="{
    content: 'MY TOOLTIP',
    placement: 'bottom',
    trigger: 'click',
    autoHide: true
  }"
>BUTTON</button>
```

Example: https://codesandbox.io/s/vue-template-kl5fy

anyone know how to make this?

**Comment by brunokunace** [comment]
@Akryum have any suggest to make it?

**Comment by trdonnisedavid** [comment]
Same issue, but it is fixed in the 3.0.0 version. 

https://jsfiddle.net/rgzmsq4y/7/

**Comment by derMart** [comment]
The opposite problem appears for trigger: 'hover', then autoHide: false does not work and a click will destroy the tooltip. Nice that this will be fixed in 3.0.0. When will this be released? npm still installs 2.0.3...

**Comment by derMart** [comment]
...and as it seems there are some API changes in version 3it would be very nice to fix this also in version 2

**Comment by Akryum** [comment]
See: https://github.com/Akryum/v-tooltip/issues/517#issuecomment-752787516

**Comment by atilkan** [comment]
It would be nice to have this fix in version 2 as well.
