### ISSUE TITLE
Real time render tooltip if necessary？

### ISSUE THREAD

**Issue by IndexXuan** [Akryum/v-tooltip#35]
Thanks for v-tooltip ~
It was found that v-tooltip calulate position when inited，could you give me the prop / option to real time render it?
Since we somtimes use it in an `Expansion panel Component`, each item was hidden when init, So was the tooltip. The tooltip shown with wrong position after that.

Feature request and Best Wishes! Thank you~

**Comment by Akryum** [comment]
Use at your own risk (internals): `this.$refs.myElement._tooltip.popperInstance.update()`
