### ISSUE TITLE
Disable auto placement while scrolling.

### ISSUE THREAD

**Issue by kamrana** [Akryum/v-tooltip#371]
If the popover is on a page with scrolling and the placement is defined as 'top-start'. It automatically changes to 'bottom-start' when we try to scroll down. Is there a way to disable this feature?

**Comment by kamrana** [comment]
Figured it out use the popperOptions and set the flip modifier to false
`'modifiers': {
     'flip': { enabled: false }
}`

**Comment by michaelschomburg** [comment]
this solution did not work like that for me. I had to remove the quotes around modifiers and flip
` popperOptions="modifiers:{flip:{ enabled: false }}" `
