### ISSUE TITLE
[Feature Request] autoHideDelay option

### ISSUE THREAD

**Issue by ThomasKientz** [Akryum/v-tooltip#377]
Hi and thank you for this great lib.

Material Design specs about tooltip states that tooltips must  ["fade out over 75ms."](https://material.io/components/tooltips/#behavior)

I haven't find an option to set this. Is it possible to add one ?

Cheers

**Comment by Akryum** [comment]
Use the delay option.

**Comment by ThomasKientz** [comment]
@Akryum 

I've already used it for the enter delay (150ms). We need a second one for the exit delay :

Material specs :
> Over 150ms, tooltips fade in and scale up using the deceleration curve. They fade out over 75ms.

**Comment by Akryum** [comment]
```
delay: { show: 150, hide: 75 }
```
