### ISSUE TITLE
Please could you explain how to set container and boundariesElement properties?

### ISSUE THREAD

**Issue by Redrica** [Akryum/v-tooltip#378]
_container - Selector: Container where the tooltip will be appended (e.g. 'body').
boundariesElement - DOM element for the tooltip boundaries._

what kind of selector I need?
I tried to use a classname there but it didnt work.
I have a set of cards with tooltips in them and I want to place tooltips' element inside a card instead of body.
and the same question about boundariesElement.

Thanks in advance!

**Comment by idrislab** [comment]
I think you must do something like 

```js
const boundariesElement =  document.querySelector('#boundariesElementl');
```

**Comment by chasefleming** [comment]
I tired this. No luck. The tooltip is still going outside the container I specified as the boundariesElement:

```
v-tooltip="{
  content: 'blah',
  show: true,
  trigger: 'manual',
  boundariesElement: boundariesElement
}"
```

In this snippet, boundariesElement is using the example:

`const boundariesElement =  document.querySelector('#boundariesElement');`

How do we get it to work?
