### ISSUE TITLE
Replace large lodash-merge dependency (15kB minified) with something smaller.

### ISSUE THREAD

**Issue by petr001** [Akryum/v-tooltip#383]
I find `lodash/merge` as quite big dependency, especially it's used only once in codebase. It can be replaced with much smaller implementation, for example https://gist.github.com/ahtcx/0cd94e62691f539160b32ecda18af3d6.

**Comment by petr001** [comment]
This seems to be a good alternative: https://www.npmjs.com/package/deepmerge

**Comment by Akryum** [comment]
`lodash/merge` doesn't bring the whole lodash library.

**Comment by petr001** [comment]
According to my tests `loash/merge` dependency really adds 15,5kB minified. And I know, it's not a whole library :-(

**Comment by Akryum** [comment]
Not what bundlephobia shows: https://bundlephobia.com/result?p=v-tooltip@2.0.2

**Comment by petr001** [comment]
I've also found bug in `rollup.config.es.js`, where `lodash` is present, but is ignored. The right value should be `loadash/merge`.

Then bundled demo site vendor js with lodash is: 865.42 KiB
And with deepmerge is: 851.07 KiB

**Comment by petr001** [comment]
Is it OK to create pull request replacing lodash dependency with much smaller deepmerge implementation? I'm really not happy with extra 14.3kB minified code because of one usage in whole codebase..
