### ISSUE TITLE
Inconsistent browser support

### ISSUE THREAD

**Issue by thomicdk** [Akryum/v-tooltip#39]
Both Vue.js and Tooltip.js support Internet Explorer 10 and 11, but v-tooltip does not. 

There are dependencies on `Object.assign` and `Symbol` which are not supported in IE. But then again, those dependencies are just a result of Babel transpiling Object spread and a for-of loop. Hence adding IE support is probably just a matter of tweaking the Babel config.

What are your thoughts about this?

**Comment by Akryum** [comment]
There is a great chance you already uses [babel-polyfill](https://babeljs.io/docs/usage/polyfill/) in your app to support 4+ years old browsers. Or you can add [this tiny polyfill](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Polyfill) made by Mozilla.
