### ISSUE TITLE
npm install did nothing

### ISSUE THREAD

**Issue by stevenlupo** [Akryum/v-tooltip#392]
Ran the npm install, but it did not actually install anything:
```
C:\...>npm install --save -v-tooltip
audited 5 packages in 1.05s
found 0 vulnerabilities
```
yet nothing was installed.

**Comment by stevenlupo** [comment]
Sorry, I decided not to use this package, although I didn't resolve this problem.

**Comment by Akryum** [comment]
The command should be `npm install --save v-tooltip`

**Comment by stevenlupo** [comment]
Wow, I can't believe I didn't see notice the dash! Thanks.
