### ISSUE TITLE
Async does not work with parameters

### ISSUE THREAD

**Issue by craigg75** [Akryum/v-tooltip#393]
This works:
`<div v-tooltip="{content:asyncMethod}></div>`

This does not work:
`<div v-tooltip="{content:asyncMethod()}></div>`
nor does this:
`<div v-tooltip="{content:asyncMethod(99)}></div>`

**Comment by Ruinevo** [comment]
it works for me:
`<div v-tooltip="{content: asyncMethod.bind(null, 99) }></div`
