### ISSUE TITLE
no popups on <input type="button" :disabled="true" />

### ISSUE THREAD

**Issue by reed-jones** [Akryum/v-tooltip#403]
Disabled buttons don't seem to be able to have popups, which would be nice for explaining why the button is disabled. https://codesandbox.io/s/v-tooltip-disabled-button-fj0oj

**Comment by p0psicles** [comment]
The same goes for `<input type="text" disabled="disabled">`
Did you find a solution to this?

**Comment by p0psicles** [comment]
Found this as a workaround: https://github.com/Akryum/v-tooltip/issues/125

**Comment by Akryum** [comment]
Duplicate of #125
