### ISSUE TITLE
Accessibility concerns - ARIA attributes must conform to valid values

### ISSUE THREAD

**Issue by davidraijmakers** [Akryum/v-tooltip#432]
I am getting some warnings from axe and tools like lighthouse on pages like https://akryum.github.io/v-tooltip/#/ that there is a accessibility issue regarding the hidden popovers in the dom but the aria-describedby that is present. Axe says the following:

ARIA attributes must conform to valid values
![Screenshot 2020-01-02 at 10 44 50](https://user-images.githubusercontent.com/4717921/71660970-f5091900-2d4c-11ea-8673-71f4a748d400.png)

This is because the popovers are not by default shown and get removed after a few seconds hiding the popover.

Shouldn't this be changed by always having the popover added to the dom and let it hide/show whenever the popover is activated?

**Comment by liyasthomas** [comment]
`[aria-*] attributes do not have valid values`

This issue is reducing Lighthouse score.

**Comment by lifenautjoe** [comment]
@Akryum ping 🙏

**Comment by beckybair** [comment]
this is also showing up on our AQA audits - a fix would be wonderful, please...

**Comment by mindsurfer** [comment]
Is there any update on this ? I have literally just been tasked with solving this issue for work and if I can't, I have to find alternative popup solution. @Akryum ?
Thanks.
