### ISSUE TITLE
Fails in production environment due to CSP issues

### ISSUE THREAD

**Issue by adamreisnz** [Akryum/v-tooltip#433]
![image](https://user-images.githubusercontent.com/490562/71775653-27cf3d80-2fe9-11ea-8d42-f8643b2c7e08.png)

Any thoughts?

**Comment by adamreisnz** [comment]
Looks like it was a typo in the CSP that was to blame

**Comment by nirmalgupta** [comment]
> Looks like it was a typo in the CSP that was to blame

I am also getting the same issue. But I am not able to find typo in our case. Can you please share more info around it. May be it will help us.
- Regards

**Comment by adamreisnz** [comment]
We had a missing semi colon:

`...connect-src https: wss: script-src https: ...`

-->

`...connect-src https: wss:; script-src https: ...`
