### ISSUE TITLE
2.0.3 typescript error

### ISSUE THREAD

**Issue by doits** [Akryum/v-tooltip#459]
I updated to `2.0.3` but it now gives a typescript error:

```
ERROR in .../node_modules/v-tooltip/types/index.d.ts(3,1):
3:1 Top-level declarations in .d.ts files must start with either a 'declare' or 'export' modifier.
    1 | import Vue, { VueConstructor, DirectiveOptions, PluginFunction } from 'vue';
    2 |
  > 3 | const vToolTip: PluginFunction<any>;
      | ^
    4 | export default vToolTip;
    5 |
    6 | export const VPopover: VueConstructor<Vue>;
```

I *think* it is resolved by changing lines 3 and 4 to one line:

```ts
export default const vToolTip: PluginFunction<any>;
```

At least with this I have no typescript error anymore, but I am not sure if this changes the meaning.

**Comment by mad4hit** [comment]
same problem here. but i suggest to use:

`declare const vToolTip: PluginFunction<any>;
export default vToolTip;`

**Comment by cristianireyes** [comment]
As a partial solution you can add `"skipLibCheck": true` in your _**tsconfig.json**_

**Comment by cristianireyes** [comment]
> As a partial solution you can add `"skipLibCheck": true` in your _**tsconfig.json**_

I sent [pull request](https://github.com/Akryum/v-tooltip/pull/462) with solution to fix #459

**Comment by connorshea** [comment]
FYI: To avoid getting these issues when upgrading packages, you can run `npm run tsc` or `yarn run tsc` in your CI to verify TypeScript is able to compile your code. I'm not sure if `tsc` would work for v-tooltip itself since I don't think the entire project is written in TypeScript?

I didn't have this in my CI until now, so this issue bit me, but I'm glad I have another safeguard in my CI :D

**Comment by solidevolution** [comment]
What about this issue? @Akryum ?

**Comment by imwillhang** [comment]
@Akryum pls help @Akryum

**Comment by solidevolution** [comment]
A good solution instead of using this library was to implement an own vue component with plain, configurable TippyJS. With that, also PropperJS Bugs are gone.

**Comment by jwkicklighter** [comment]
@solidevolution Not sure how the PopperJS bugs can be gone with TippyJS since it [uses popper](https://github.com/atomiks/tippyjs/blob/master/package.json#L155) under-the-hood...

Regardless, that doesn't really help with this issue at all.

**Comment by okandas** [comment]
@imwillhang, @solidevolution and @Akryum  [https://github.com/Akryum/v-tooltip/pull/564](pull request that fixes this) .. We should be good to go

**Comment by elwin013** [comment]
Locally working fix based on: https://github.com/stephenmathieson/node-tlds/issues/11
1. create file `src/vtooltip.d.ts` with content:
```
import Vue, {VueConstructor, DirectiveOptions, PluginFunction} from 'vue';

declare const vToolTip: PluginFunction<any>;
export default vToolTip;

export const VPopover: VueConstructor<Vue>;
export const VClosePopover: DirectiveOptions;
export const VTooltip: DirectiveOptions;
```
2. Add path in `tsconfig.json` in `compileOptions` section:
```
"paths": {
...
      "v-tooltip": [
        "src/vtooltip.d.ts"
      ],
...
    },
```
