### ISSUE TITLE
does this module support <button> tag only?

### ISSUE THREAD

**Issue by juicycool92** [Akryum/v-tooltip#461]
Hello,

as mention on title, i want to use tooltip on another tag like div.

but its seems not work :/

does this module works only in button tag? or i use wrong?

Thanks.

**Comment by Akryum** [comment]
I works on any element that can receive mouse events. 🐱

**Comment by juicycool92** [comment]
> I works on any element that can receive mouse events.

Thankyou! Ill try again!
