### ISSUE TITLE
ES6 syntax in minified distribution files

### ISSUE THREAD

**Issue by Krisell** [Akryum/v-tooltip#466]
In the CDN hosted minified JS file, https://unpkg.com/v-tooltip@2.0.3/dist/v-tooltip.min.js, ES6 syntax is used with the keywords `const` and `let`. This causes problems in IE11 and older versions of Safari (and in very old versions of other browser as well).

Is this intended? If so, I suggest adding a note about browser support to the README.

**Comment by Kolobok12309** [comment]
+1, Have same problem

**Comment by JoelPintoRibeiro** [comment]
Same issue here , had to rollback to 2.0.2

**Comment by njleonzhang** [comment]
same bug

**Comment by johannes-z** [comment]
@devs:
This happens because `vue-runtime-helpers` isn't transpiled, as it's excluded by the babel config:
https://github.com/Akryum/v-tooltip/blob/master/build/rollup.config.base.js#L21

You'll have to include `vue-runtime-helpers` like this `exclude: /node_modules(?!.*vue-runtime-helpers)/`

**Comment by Akryum** [comment]
`const` and `let` are supported by IE11. If you need to support older browsers, please [transpile your dependencies](https://cli.vuejs.org/config/#transpiledependencies).
