### ISSUE TITLE
Custom classes are not always added to the tooltip element 

### ISSUE THREAD

**Issue by ilearnio** [Akryum/v-tooltip#47]
After I upgraded from "2.0.0-beta.5" to latest "2.0.0-beta.12" the classes that I have added to the `v-tooltip="{ classes: '...' }"`are sometimes not adding to the tooltip element. So some one or two first mouse-overs after page reloading look fine, i.e. the classes applied well, but after that it stops adding these classes. 

To be more specific I'm adding these options to my tag's `v-tooltip` attribute.

```
classes: 'vue-tooltip-boxes-small',
container: '.item-form-toolbar',
popperOptions: {
  modifiers: {
    offset: {
      offset: 3
    }
  }
}
```

**Comment by lukasborawski** [comment]
+1

**Comment by lukasborawski** [comment]
@Akryum any chance to fix this?

**Comment by canvural** [comment]
See also #40 and #41

**Comment by lukasborawski** [comment]
Jo, there is waiting PR for this, can we merge it?

**Comment by lukasborawski** [comment]
@Akryum i see it's merged, can you please update NPM? Thx.
