### ISSUE TITLE
v-tooltip directive content=html no longer displays properly

### ISSUE THREAD

**Issue by escofield** [Akryum/v-tooltip#472]
having upgraded to 3.0.0-alpha.13 some of our tooltips that provided html content as part of the directive options.content now displays the html as text within the tooltip.
Reverting back to 3.0.0-alpha.11 resolves this issue.  :(

**Comment by alexlyul** [comment]
same issue

**Comment by Akryum** [comment]
HTML is enabled by default. You need to either enable it on the directive with `contentHtml` or enable it globally in the global options.
