### ISSUE TITLE
Render popover content when showing the popover for the first time

### ISSUE THREAD

**Issue by rootman** [Akryum/v-tooltip#496]
Currently the popover contents are rendered directly. It would be great to have an option, so that the popover slot is only rendered when the popover is shown for the first time.

The reason for that is a performance issue that I am facing. I am rendering a list of popover components. The initial rendering takes a lot of time, because all the components in the popover are rendered when the list is rendered. To solve that issue, I have added a `v-if="opened"` to the popover contents and use `@show="opened = true"`. That way, the popover contents are rendered, when the popover is opened for the first time.

What do you think about integrating this into v-tooltip directly. When I find the time, I will look into it, should not be a big thing.

**Comment by Akryum** [comment]
Fixed in v3: https://github.com/Akryum/v-tooltip/commit/77d292755d4f0518a069b13d4c713d33197630cb
