### ISSUE TITLE
Popper 2.0

### ISSUE THREAD

**Issue by Ore4444** [Akryum/v-tooltip#498]
I noticed v-tooltip is dependent on popper 1.x.
Since 2.x is more than a small improvement, what would it take to upgrade?

**Comment by diegodhuart** [comment]
+1

**Comment by solidevolution** [comment]
The tooltip currently flips only on one axis, if content overflows the viewport.
Maybe the new popper version could fix this behavior? (flip, fallbackPlacements)

<img width="422" alt="flip-top" src="https://user-images.githubusercontent.com/6850773/85536363-541c5c00-b613-11ea-8ea6-af8f9e525110.png">
<img width="417" alt="bottom" src="https://user-images.githubusercontent.com/6850773/85536373-554d8900-b613-11ea-9bc1-15c3793e4d0d.png">

**Comment by mkalayci35** [comment]
+1

**Comment by tchret** [comment]
> The tooltip currently flips only on one axis, if content overflows the viewport.
> Maybe the new popper version could fix this behavior? (flip, fallbackPlacements)
> 
> <img alt="flip-top" width="422" src="https://user-images.githubusercontent.com/6850773/85536363-541c5c00-b613-11ea-8ea6-af8f9e525110.png">
> 
> <img alt="bottom" width="417" src="https://user-images.githubusercontent.com/6850773/85536373-554d8900-b613-11ea-9bc1-15c3793e4d0d.png">

https://github.com/Akryum/v-tooltip/issues/144#issuecomment-425366453

**Comment by Akryum** [comment]
Closed in https://github.com/Akryum/v-tooltip/commit/8ccd62d0b99b1e57902d85b78c4d9937548f62ef
