### ISSUE TITLE
[Vue warn]: Failed to resolve directive: tooltip

### ISSUE THREAD

**Issue by sofuxro** [Akryum/v-tooltip#50]
Using the example from the README, I get `[Vue warn]: Failed to resolve directive: tooltip`

on Vue 2.4.4 and Webpack 3.6.0

**Comment by sofuxro** [comment]
I've test it on a fresh project and it works. I need to figure out what is wrong with my build... maybe webpack encore

**Comment by tbsvttr** [comment]
Same problem here, but the hint by @sofuxro did not help. It changed nothing.

**Comment by obrienmd** [comment]
I'm having similar issues with Vue 2.5.2, but changing import from capitalized 'Vue' imports the runtime-only Vue package, meaning my single-file components can't compile their templates.

**Comment by Akryum** [comment]
Do you still have the issue with the new release?

**Comment by obrienmd** [comment]
Sorry, I had to move over to a different library for the project I was trying to add it to. I'll give it a shot if I have a chance, but I wouldn't hold my breath :(

**Comment by danpatnate** [comment]
Same issue, even when using Vue 2.5.2

**Comment by Akryum** [comment]
Do you have a repro to share please?

**Comment by Akryum** [comment]
If you still have the issue with the latest release, please let me know in a comment.

**Comment by jongravois** [comment]
@obrienmd which library did you move to? I am getting 928 console errors of 'Failed to resolve directive: tooltip' -- my stakeholders require tooltips on any icon in use on a page and now this package seems foobar.

**Comment by Akryum** [comment]
Did you try this?

```js
import Vue from 'vue'
import { VTooltip, VPopover } from 'v-tooltip'

Vue.directive('tooltip', VTooltip)
Vue.component('v-popover', VPopover)
```

Also, could you log the result of the import?

```js
import VTooltip from 'v-tooltip'

console.log(VTooltip)
```

Make sure you are doing all of this before launching the app with `new Vue`. Plugins should always be installed before that.

**Comment by jongravois** [comment]
```
VTOOLTIP 
{options: {…}, bind: ƒ, update: ƒ, unbind: ƒ}
bind
:
ƒ bind(el, _ref)
options
:
{tetherOptions: {…}, defaultClass: "vue-tooltip-theme"}
unbind
:
ƒ unbind(el)
update
:
ƒ update(el, _ref2)
__proto__
:
Object
```

**Comment by jongravois** [comment]
```
require('./bootstrap');

import Vue from 'vue';
import axios from 'axios';
import Vuex from 'vuex';

import { store } from './vuex/store';
import { VTooltip } from 'v-tooltip';

Vue.use(Vuex);
Vue.use(VTooltip);

Vue.directive('tooltip', VTooltip);
console.log('VTOOLTIP', VTooltip);

import './components';
import './filters';

axios.defaults.headers.common = {
    'X-CSRF-TOKEN': window.Laravel.csrfToken,
    'X-Requested-With': 'XMLHttpRequest'
};

const app = new Vue({
    el: '#app',
    store
});
```

**Comment by Akryum** [comment]
You are only getting the directive here, change `import { VTooltip } from 'v-tooltip'` to `import VTooltip from 'v-tooltip'` to get the entire plugin.

**Comment by jongravois** [comment]
```
require('./bootstrap');

import Vue from 'vue';
import axios from 'axios';
import Vuex from 'vuex';

import { store } from './vuex/store';
import VTooltip from 'v-tooltip';

Vue.use(Vuex);
Vue.use(VTooltip);

Vue.directive('tooltip', VTooltip);
console.log('VTOOLTIP', VTooltip);

import './components';
import './filters';

axios.defaults.headers.common = {
    'X-CSRF-TOKEN': window.Laravel.csrfToken,
    'X-Requested-With': 'XMLHttpRequest'
};

const app = new Vue({
    el: '#app',
    store
});
```

no more console errors but also no tooltips either

**Comment by Akryum** [comment]
You should have:

```js
require('./bootstrap');

import Vue from 'vue';
import axios from 'axios';
import Vuex from 'vuex';

import { store } from './vuex/store';
import VTooltip from 'v-tooltip';

Vue.use(Vuex);
Vue.use(VTooltip);

console.log('VTOOLTIP', VTooltip);

import './components';
import './filters';

axios.defaults.headers.common = {
    'X-CSRF-TOKEN': window.Laravel.csrfToken,
    'X-Requested-With': 'XMLHttpRequest'
};

const app = new Vue({
    el: '#app',
    store
});
```

**Comment by jongravois** [comment]
By the way, I wanted to apologize for the "this package is foobar' comment ... I was frustrated. The reality is that I use your package on EVERY page of my app as much as 20 - 30 times per page ... the notation is precise and concise and absolutely solved my problem before.

It's a GREAT package but now something is broken ... please accept my apology.

**Comment by Akryum** [comment]
Really, the only code needed to use the plugin is:

```js
import VTooltip from 'v-tooltip';
Vue.use(VTooltip);
```

This code needs to be put before `new Vue` like any other Vue plugin.

**Comment by Akryum** [comment]
@jongravois Don't worry, I know that feeling. :smile: Let's work out your issue! 👍

**Comment by jongravois** [comment]
LOL ... removing the "Vue.directive('tooltip', VTooltip);" now gives me a tooltip BUT it appears on mouse over and STAYS after mouse out ... LOL, I have 17 tooltips showing on this page now

**Comment by Akryum** [comment]
Are you using the latest version? Did you got anything interesting in the browser console?

**Comment by jongravois** [comment]
console is quite but the styling is also gone

![image](https://user-images.githubusercontent.com/6824241/32553039-5e6c70ca-c45b-11e7-833b-9324179a3954.png)

**Comment by Akryum** [comment]
Did you use the plugin before `2.1.x`?

**Comment by Akryum** [comment]
What is the CSS you use for the tooltips?

**Comment by jongravois** [comment]
yes and it worked beautifully

**Comment by jongravois** [comment]
I am using "v-tooltip@1.1.6"

**Comment by Akryum** [comment]
So you are trying to update to `2.0.x` and are getting issues? Some things changed since the `1.x` versions, like the placement engine (now popper.js) and a few other attributes changes. But what changed most is the CSS you need to write for the tooltips. Maybe you could share your CSS related to the tooltips so I can 'upgrade' it.

**Comment by jongravois** [comment]
I do not add any additional CSS for the tooltips I just used the package out of the box which was more than sufficient before

**Comment by Akryum** [comment]
Okay, so add [this style](https://github.com/Akryum/v-tooltip#style-examples) to your project and let me know if it works.

**Comment by Akryum** [comment]
Also, it is possible that bootstrap is conflicting with this style. Could you check in the Style dev tools if some bootstrap classes are applied to the tooltips? (The tooltips are added to the `<body>` element by default.)

**Comment by jongravois** [comment]
I am working on a new app this morning ... I ran "npm install --save v-tooltip" on the new app and copied over the setup from an existing app ... I got 90+ console errors. When I regained consciousness, I uninstalled the package and forced it to version 1.1.6 thinking version 2.0 was the issue

I don't use any Bootstrap styling at all ... I use Bulma.

I am trying the css you sent now

**Comment by jongravois** [comment]
should I try the upgrade again?

**Comment by Akryum** [comment]
> should I try the upgrade again?

Yes.

**Comment by jongravois** [comment]
so "npm uninstall --save v-tooltip" and then "npm install --save v-tooltip" ???

**Comment by Akryum** [comment]
Open your `package.json` file and change the version of `v-tooltip` to `^2.0.0-rc.16` and then run `npm i`.

**Comment by jongravois** [comment]
I did the upgrade and added your stylesheet ... it is working beautifully again ... crisis abated ... wrists unslashed! 

THANK YOU VERY MUCH FOR YOUR TIME AND ATTENTION!

**Comment by Akryum** [comment]
Glad it works now! :smile:

**Comment by rasko-lazic** [comment]
@Akryum Just a quick question, just to see if its a mistake on my side or a bug. The plugin is installed and tooltip directive works perfectly, the issue is using v-popover component, I just get an error

`[Vue warn]: Unknown custom element: <v-popover> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`

Should maybe v-popover component be registered in `components` section where its being used?

**Comment by Akryum** [comment]
Well, `Vue.use(VTooltip)` should be enough if you are using the most recent versions of the package.

**Comment by rasko-lazic** [comment]
You are completely right, thanks for a quick response

**Comment by FEA5T** [comment]
```
var focus = {
	inserted: function (el) {
		el.focus()
	}
};
console.log(focus);
Vue.directive('focus', focus);
```

This code runs before initializing the main app.  I am using the akryum:vue package for meteor with routing.

Result:

`main.js:369 [Vue warn]: Failed to resolve directive: focus`

@Akryum I honestly cannot understand why this could be failing.

![image](https://user-images.githubusercontent.com/2647403/37311355-29dd5210-2604-11e8-9ed9-f348070563be.png)

The directive is registered in the global vue instance, visible here, and I am using the example from vue docs...any ideas?

**Comment by Akryum** [comment]
Your directive is not a valid Vue 2.x directive, you need to use `bind` instead of `inserted`.

**Comment by FEA5T** [comment]
@Akryum Thanks for the reply.  I just tested using bind instead, but I receive the same error.  Also, vue docs 2.0 list inserted as valid here: https://vuejs.org/v2/guide/custom-directive.html

Do you have any other thoughts here?  I checked the akryum:vue demo here: https://github.com/meteor-vue/vue-meteor-demo/tree/master/src/imports and couldnt find any directive examples in use.  Right now the Vue.directive() call in my code in inside Meteor.startup.  Not sure where to go from here except not use directives.

**Comment by Akryum** [comment]
Did you try registering the directives outside of `Meteor.startup`?

**Comment by FEA5T** [comment]
I tried this, but could not get it to register at all, and since I .  Clearly vue is picking up the directive because you can see it registering in $options on my main vue app instance.  

![image](https://user-images.githubusercontent.com/2647403/37372095-d99d676a-26ce-11e8-9fa6-d82f973cda9d.png)

As you can see in the image above, this is about as simple as I can possibly register the directive.

**Comment by Akryum** [comment]
How do you import Vue in your files?

**Comment by FEA5T** [comment]
in main.js in meteor client directory:

![image](https://user-images.githubusercontent.com/2647403/37375141-934299fe-26db-11e8-9202-79b4485512ce.png)

**Comment by Akryum** [comment]
Coud you change it to `import Vue from 'vue'`? Also do you import Vue from other files as well?

**Comment by FEA5T** [comment]
@Akryum Yes, but when I do that, my app doesn't run.

I am also using vuex and vue router as a script in html because they just do not import properly and I don't know why.

**Comment by fgilio** [comment]
I'm getting this message too, it's the only package with which it's happening. Anything I can try?

**Comment by CapedHero** [comment]
When I had registered the directive locally, the errors disappeared.
```javascript
import { VTooltip } from "v-tooltip";
import Vue from "vue";

const Component = Vue.extend({directives: { tooltip: VTooltip }});
```

**Comment by fgilio** [comment]
> When I had registered the directive locally, the errors disappeared.
> 
> ```js
> import { VTooltip } from "v-tooltip";
> import Vue from "vue";
> 
> const Component = Vue.extend({directives: { tooltip: VTooltip }});
> ```

Then it sounds it was the same problem as mine
