### ISSUE TITLE
Distribution file `v-tooltip.min.js` contain `const` and it breaks old browsers

### ISSUE THREAD

**Issue by chenxeed** [Akryum/v-tooltip#503]
Hello, and thanks for the awesome directive!

I'm not sure what are the browser compatibility supported for `v-tooltip`, but appearantly when I use it in my application, it breaks old browser that doesn't support ES6 syntax such as `const`.

I checked and it's because the distribution file `v-tooltip.min.js` contains `const` in the script.

May I request for the distribution file be polyfilled so it also compatible for old browser?

Thank you again!

**Comment by chenxeed** [comment]
Same issue reported here: https://github.com/Akryum/v-tooltip/issues/503

**Comment by movingStars** [comment]
Same issue
Has solved?
