### ISSUE TITLE
Offset option doesn't do anything?

### ISSUE THREAD

**Issue by tylerbwoodridge** [Akryum/v-tooltip#51]
I haven't been able to see the offset option work so far. My tooltip looks like this:
`<span v-tooltip="{content: 'hello world', placement: 'top-end', offset: 100}"></span>`

**Comment by OwenMelbz** [comment]
I've never been able to get any of the properties working, changing the placement for me doesn't even work :(

The only property I seem to be able to change is the `content`

**Comment by Akryum** [comment]
This is an issue with tooltip.js. I'll make a PR. In the meantime, I fixed this inside v-tooltip in the rc.2 release.

**Comment by edDimensi** [comment]
DefaultOffset not work anyway

**Comment by Akryum** [comment]
@edDimensi Could you try again with the latest release?

**Comment by edDimensi** [comment]
yes, now it's work

**Comment by yowzadave** [comment]
<img width="185" alt="tooltip" src="https://user-images.githubusercontent.com/18472347/44942397-cb696780-ad7d-11e8-9c26-10366a54cb86.png">
I'm experiencing what seems to be a similar problem? My tooltip is always located directly on top of my button element; changing the `offset` property has no effect on its location. I'm placing the tooltip like so:
```
<button :class="{active}"
      :disabled="disabled"
      class="w-8 h-8 flex items-center justify-center"
      v-tooltip.bottom="{content: feature.displayName, offset: 100}"
      @click="handleClick">
    <component class="w-3/5 pointer-events-none"
        :is="icon" />
  </button>
```

**Comment by ivansieder** [comment]
@yowzadave I have tried using your code in an app and it works as expected. Are you using the latest version of the plugin? Are you sure you're not overwriting the positioning of the tooltip with some custom css/js? Do you have any complete code example to test this with? Because right now I can't reproduce this issue.

**Comment by yowzadave** [comment]
@ivansieder thanks for the suggestions. After some exploration, I was able to identify the problematic style rule: a grandparent div had the rule `overflow-y:hidden;` applied, which for some reason keeps the tooltip from being correctly positioned.

**Comment by ivansieder** [comment]
That's on purpose, as the plugin is made to prevent being positioned in overflows. (That's the preventOverflow property of popper.js)

**Comment by yowzadave** [comment]
Thank you!
