### ISSUE TITLE
Closing tooltip on outside click

### ISSUE THREAD

**Issue by ballonura** [Akryum/v-tooltip#517]
Hello, i have an <svg> tooltip target with trigger: 'click', and i need option to close the tooltip not only by clicking again on the target element (svg). There is anyway do that?
Thx. :)

**Comment by ajingopi-bridge** [comment]
@ballonura Have you got a solution for this?
@Akryum I have created a fiddle for this issue, do you have a solution for this? Please see the fiddle.

I need to close all the tooltips when click outside

**Comment by ballonura** [comment]
@ajingopi-bridge No, change the trigger to "hover" :\

**Comment by ajingopi-bridge** [comment]
Huh hover don't work in mobiles though, I tested with alpha version but behaves completely different with same code.

**Comment by ballonura** [comment]
I use "hover click" trigger string.

**Comment by ajingopi-bridge** [comment]
Means can use both hover and clicke inside trigger?

**Comment by ballonura** [comment]
True.

**Comment by ajingopi-bridge** [comment]
Yeah that's possible but a weird fix, all the tooltip pligins I used have a feature to close when click outside. I should search and find a better tooltip it seems..!! It's not at all hard to find and close tooltips when clicked ouside from within plugin. Dont know why the author skipped it..!!

**Comment by ballonura** [comment]
You are more then welcome to PR it, help to the community.

**Comment by ajingopi-bridge** [comment]
True but another time been busy with things for sometime..!!

**Comment by Akryum** [comment]
Use the `autoHide` option.

**Comment by Akryum** [comment]
Sorry for the mistake. The autoHide option for the tooltip directive is a bit different, it just hide the tooltip on hover or click on the tooltip content. It is fixed in v3 since it's using the full component for both component and directive usage.

**Comment by atilkan** [comment]
It can be nice to have this fix on version 2.
