### ISSUE TITLE
How do you use the v-tooltip with a router-link?

### ISSUE THREAD

**Issue by ChadTaljaardt** [Akryum/v-tooltip#52]
Hello, 

I want to use this on my router-link,  but its not working when i hover over the button.

```
    <router-link :to="{ name: 'AccountsEdit', params: { id: item.id }}" v-tooltip="'tester for the tooltip system'">
        {{ item.name }} {{ item.description }}
    </router-link>
```

**Comment by SHA-256** [comment]
I would create a container within the router-link to which I would then assign the tooltip.

**Comment by Akryum** [comment]
I don't reproduce this in the demo. [Here](https://github.com/Akryum/v-tooltip/blob/c919765779f9d08d3c5d209e247bf32ba41aeab3/demo-src/src/PageHome.vue#L5-L13) is the relevant code.

**Comment by ChadTaljaardt** [comment]
@Akryum @SHA-256 I tried this and when i hover over the tooltip and look in the inspect element console i see this : 

```
<div class="tooltip vue-tooltip-theme" role="tooltip" id="tooltip_v2g6d8r1n4" aria-hidden="false" x-placement="top" style="position: absolute; transform: translate3d(696px, 578px, 0px); top: 0px; left: 0px; will-change: transform; display: none;">
    <div class="tooltip-arrow" style="left: 0px;"></div>
    <div class="tooltip-inner">Installation Instruction page</div>
</div>
```

But nothing appears on the screen. Im using the demo code on the test page.

**Comment by Akryum** [comment]
Did you setup the [tooltip CSS](https://github.com/Akryum/v-tooltip#style-examples)?

**Comment by ChadTaljaardt** [comment]
Missed that, seems to be working fine now :)
