### ISSUE TITLE
Ability to replace "v-popover" and "trigger" class

### ISSUE THREAD

**Issue by rockmandash** [Akryum/v-tooltip#529]
These two might conflict with other css libraries.

https://github.com/Akryum/v-tooltip/blob/fa672f6d6d2004d9cb285ce4551f12c9ca1f6540/src/components/Popover.vue#L3
https://github.com/Akryum/v-tooltip/blob/fa672f6d6d2004d9cb285ce4551f12c9ca1f6540/src/components/Popover.vue#L8

**Comment by Akryum** [comment]
Fixed in v3 as it would be a breaking change. All classes in v3 will use a `v-popper` prefix.
