### ISSUE TITLE
auto-hide: true activates on mouse-up instead of mouse-down

### ISSUE THREAD

**Issue by SimonDatapas** [Akryum/v-tooltip#530]
When using the auto-hide option, the popover closes when clicked outside of the popover.
This triggers on the mouse-up event.

In my use-case, I would like to have a popover triggered by click and auto-hide on true, so that the popover closes when clicking somewhere else.
However, when I select something within my popover, but release the mousebutton outside of the popover when selecting something, the popover still closes.
I believe this happens because the trigger for this is defined on mouse-up instead of mouse-down, wich to me seems illogical.

Is there any way to change this? Or could this be fixed from withing this package?

**Comment by trickpeeraze** [comment]
How about this case so far?
