### ISSUE TITLE
Clear event listeners on auto destroy

### ISSUE THREAD

**Issue by edDimensi** [Akryum/v-tooltip#55]
On dispose(), onScroll and onResize events listeners not removed.

**Comment by edDimensi** [comment]
I think this problem in tooltip.js, not in your plugin. But in that example, tooltip.js clearing scroll event.
https://codesandbox.io/s/38r4z1pk1

**Comment by edDimensi** [comment]
If you wait until the timer ends and then call _dispose (), then the events are not cleaned up

**Comment by edDimensi** [comment]
You have conflict with this 
https://github.com/FezVrasta/popper.js/blob/0d42238960a0e82e4494fd9ab5c72dc79720106a/packages/tooltip/src/index.js#L255-L266

**Comment by Akryum** [comment]
Do you still have this issue with the latest release?

**Comment by edDimensi** [comment]
Yes

**Comment by edDimensi** [comment]
What profit in auto clear dom? On unbind v-tooltip will be dispose. No element - no tooltip.

**Comment by Akryum** [comment]
If you have a lot of v-tooltip on the page (once I had like hundreds of them).

**Comment by Akryum** [comment]
I will need a full reproduction and explanation of what is happening and what should happen to fix this.

**Comment by edDimensi** [comment]
https://xv3rzy3xzq.codesandbox.io/
Open devtools, open elements tab, go to Event Listeners.
Hover on elements for display tooltips and click on update button in Event Listeners sidebar.
Wait until all tooltips will be deleted from dom.
Click again on button in event listers.
Change page, click on refresh button in event listeners.
![image](https://user-images.githubusercontent.com/11390039/31939395-e6f0cea4-b8c2-11e7-9e5a-ebe0c1f1c2ef.png)
