### ISSUE TITLE
Unfortunately, vue ssr is not supported

### ISSUE THREAD

**Issue by shx1545** [Akryum/v-tooltip#59]
If inscribe

**Comment by JounQin** [comment]
I add `global.Element = null` at top of my server entry as workaround for now.

**Comment by dunice-boldirev** [comment]
@JounQin  Your method helped me. Thank you!

**Comment by JounQin** [comment]
https://github.com/JounQin/Rubick/blob/master/build/webpack/vue-server.ts#L24

https://github.com/JounQin/Rubick/blob/master/build/webpack/element.js

**Comment by feedgit** [comment]
With Nuxt, you guys can config:
```
plugins: [
   { src: '~/plugins/tooltip.js', ssr: false },
]
```

Hope it helps!
