### ISSUE TITLE
popover blinks when overflow: auto

### ISSUE THREAD

**Issue by sagadav** [Akryum/v-tooltip#593]
To prevent strange behavior i use
```
:popperOptions="{
	modifiers: {
        	preventOverflow: {
        		boundariesElement: 'window',
        	},
      	},
}"
```
but now when I update the value in vuex it starts blinks

**Comment by Akryum** [comment]
Please provide a runnable minimal reproduction so I can look at this issue. :pray:

**Comment by sagadav** [comment]
The problem was solved using defaultBoundariesElement:
```
Vue.use(VTooltip, {
    defaultBoundariesElement: document.body
})
```
