### ISSUE TITLE
Add prop for target reference

### ISSUE THREAD

**Issue by dimensi** [Akryum/v-tooltip#60]
I think there are many cases where you need to specify refence manually.
I using fullcalendar and need popup for this, but i can't set every card in calendar in slots, because fullcalendar not use vue.
And i have one more case.
```
    <table-ui :headers="budgetTableHeaders"
              :rows="budgetTableRow"
              v-if="budgetTableRow">
      <template slot="row" scope="row">
        <budget-item
          :item="row"
          :activeComment="comment && comment.index === row.index"
          :currentMonth="row.index === 1"
          @openPopup="openPopup"
          @openCommentModal="openCommentModal"/>
      </template>
    </table-ui>

  <v-popover :open="Boolean(subTable)" target="subTableTarget" trigger="manual" v-if="subTable">
    <budget-sub-item :profiles="subTable.profiles"
                     :currentMonth="subTable.index === 1"
                     :familyRatio="subTable.ratio"
                     slot="popover"/>
  </v-popover>
```
event openPopup fire on every hover.
Thx in advance for your work.

**Comment by Akryum** [comment]
Thanks for posting an issue! I'm sorry but I don't understand what your problem is, could you reformulate please?

**Comment by edDimensi** [comment]
I want manually set reference target for popover component, with out using slot.
Example:
I have fullcalendar, it's jquery plugin. On click i can trigger popover, but i can't use v-popover because can't set reference slot.

**Comment by edDimensi** [comment]
```
<template>
  <div>
    <fullcalendar :events="someEvents"
                  @click="clickHandler" />
    <v-popover :ref-target="eventTarget" :open="Boolean(data)" trigger="manual" :key="data.id">
      <div slot="popover">
        {{ data.title }}
        {{ data.date }}
      </div>
    </v-popover>
  </div>
</template>

<script>
export default {
  data() {
    return {
      data: null,
      eventTarget: null,
      someEvents: [...]
    }
  },
  methods: {
    clickHandler(event, data) {
      this.data = null;
      this.eventTarget = null;

      this.eventTarget = event.target;
      this.data = data;
    }
  }
}
</script>

```

**Comment by Akryum** [comment]
Well, you can:

```js
this.$refs.myPopover.$refs.popover
this.$refs.myPopover.$refs.trigger
```

**Comment by edDimensi** [comment]
@Akryum it's not work

**Comment by Akryum** [comment]
I don't know this plugin, but here is a very basic example that should work:

```html
<v-popover @show="onShow">
  <button>click me</button>
  <div ref="target" slot="popover"></div>
</v-popover>
```

```js

methods: {
  onShow () {
    if (!this.calendar) {
      this.calendar = true
      $(this.$refs.target).fullCalendar()
    }
  },
},
```

**Comment by edDimensi** [comment]
what this? i never talk about it. I ask about how me set trigger for popover via props. 
Example:
You have 150 div elements, for every div element you must set 1 popover = 150 div + 150 popover.
Or you can create 1 popover and manual change target refence for popover.

**Comment by Akryum** [comment]
Sorry, but I didn't understand what you where saying about reference the whole time. Your issue seems to be that you need a way to change the target trigger element, correct?

**Comment by edDimensi** [comment]
yes, i want change target trigger element by props.

**Comment by edDimensi** [comment]
![screenshot_20171108_171537](https://user-images.githubusercontent.com/11390039/32553616-7307f1a6-c4a8-11e7-92a9-f86f819546a6.png)

**Comment by DaemonCahill** [comment]
@Akryum I actually have a somewhat similar issue. I have a popover that needs to be trigged many times on the same page by different elements and would like to programmatically hide/show and dynamically set the reference element. Is this currently possible?

**Comment by DaemonCahill** [comment]
@Akryum I see, it looks like you can manually set the trigger with `this.$refs.myPopover.$refs.trigger`;

**Comment by edDimensi** [comment]
@Akryum hi! I anyway can't understand how create popup from this `this.$refs.myPopver.$refs.trigger`
https://p91k69z5qj.codesandbox.io/
I create example. I all time get error `Cannot read property 'parentNode' of undefined`

**Comment by DaemonCahill** [comment]
I was able to set the trigger using the following: `this.$refs.userPopover.$refs.trigger = ref;` with a manual trigger. However, I have thus far been unsuccessful in dynamically changing the trigger using the same code once instantiated.

**Comment by bondarev** [comment]
Hi! 

Any news?

**Comment by Akryum** [comment]
Implemented in v3 alpha

**Comment by georgehrke** [comment]
Just for reference: https://github.com/Akryum/v-tooltip/blob/adbec36bda6d7a5eabb953435a4946fe7bc5c198/src/components/Popper.vue#L44L47

**Comment by vaheqelyan** [comment]
+1, i have the same issue

I can't find anything related to this in the documents
