### ISSUE TITLE
Security: Should escape HTML by default

### ISSUE THREAD

**Issue by mokkabonna** [Akryum/v-tooltip#610]
I think it is a really bad choice to NOT do escaping of potential HTML content by default.

https://github.com/Akryum/v-tooltip/blob/master/src/directives/v-tooltip.js#L31

Most template engines or frameworks as I know does escape HTML by default and you have to explicitly disable escaping to insert raw HTML.

Also Vue: https://vuejs.org/v2/guide/syntax.html#Raw-HTML

That this library does the complete opposite of vue is not good. I assumed that this library followed other defaults and best practices. My mistake for not checking though. But it is not worth it to have escaping disabled as default for the small convenience gain of not having to manually disable escaping whenever you want to display HTML that you know are safe.

Please change this. It is not good enough that you can set it globally for the app. Many people will assume good defaults or even have limited knowledge of the issue and as a result that will result in more XSS attacks.

I know this is a breaking change, but it is for safety reasons.

**Comment by Akryum** [comment]
See https://github.com/Akryum/v-tooltip/pull/286#issuecomment-576466426

Already implemented in v3.0.0 alpha.

**Comment by Akryum** [comment]
Also added a note in the readme so it's clearer: https://github.com/Akryum/v-tooltip/commit/76361cad5bd7dd096a7d39b82344d05fde0fa324

**Comment by mokkabonna** [comment]
Ok, I guess I only searched previous issues, not the pull requests.

Great with the explanation for now and really good you will change the default behaviour on next major version!

Thanks for a good library!
