### ISSUE TITLE
Problem with browser script

### ISSUE THREAD

**Issue by ArkDevon** [Akryum/v-tooltip#614]
Hello,
today i check my code and i have this "DevTools failed to load SourceMap: Could not load content for https://unpkg.com/v-tooltip.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE"

And the v-tooltip doesn't work...

You have an issue ?

![image](https://user-images.githubusercontent.com/56027857/103972981-a0258d00-516e-11eb-9d3f-4de9468d9da5.png)
![image](https://user-images.githubusercontent.com/56027857/103972997-a7e53180-516e-11eb-9a13-a27163fb5c5d.png)

Before my holiday all is good and work. And now no =/

**Comment by Akryum** [comment]
It should be back up. The error message you are reporting is just a sourcemap file, so you can safely ignore it.

BTW, I recommend you to use a version range (or a fixed version number) in the link to the unpkg CDN. [Example](https://github.com/Akryum/v-tooltip/commit/9d038b0fb14eb4538513452830f9333f2398692a#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R130) from the README I just updated.
