### ISSUE TITLE
dist file v-tooltip.min.js incompatible with IE11

### ISSUE THREAD

**Issue by dmaicher** [Akryum/v-tooltip#615]
So I noticed that the dist file `v-tooltip.min.js` shipped with the latest release is not compatible with older browsers like IE11.

This is the difference in the min file that causes the IE issues

v2.0.3

```js
mounted:function(){var e=this;Ho(), //...
```

v2.1.2
```js
mounted(){Eo(),this.$nextTick((()=>{ //...
``` 

Since I currently don't transpile node_modules with babel and don't really want to: was this change of using ES6+ in the dist file intended?

**Comment by henk23** [comment]
Looks like it's coming from https://github.com/Akryum/vue-resize, but I cannot pin it down.

**Comment by AhmedHadjTaieb** [comment]
Any solution for this problem ?

**Comment by AhmedHadjTaieb** [comment]
Solved by added this code in nuxt.config
build: {
    transpile: ['vue-tooltip', 'vue-resize'],
}

**Comment by doits** [comment]
For vue-cli:

```js
// vue.config.js
module.exports = {
  transpileDependencies: ["v-tooltip", "vue-resize"]
}
```

**Comment by Akryum** [comment]
Fixed in upcoming release

**Comment by dmaicher** [comment]
Thank you @Akryum
