### ISSUE TITLE
Documentation wrong?

### ISSUE THREAD

**Issue by capeck** [Akryum/v-tooltip#64]
Your documentation has: Vue.use(VTooltip)   but shouldn't it be Vue.use(VueTooltip) ?   That is what seems to work for me.

**Comment by Akryum** [comment]
Well, I don't think the code snippets in the documentation are wrong. Where is the issue in the docs?

**Comment by capeck** [comment]
In the Read Me in git.  For example here:
Manually install the plugin into Vue:

Vue.use(VTooltip)

**Comment by Akryum** [comment]
Oh there is [an error](https://github.com/Akryum/v-tooltip/blob/master/build/rollup.config.browser.js#L11) in the rollup configuration. 😄
