### ISSUE TITLE
Doesnt set classes correctly 3.0.0-alpha.21

### ISSUE THREAD

**Issue by djleonskennedy** [Akryum/v-tooltip#645]
Hello Akryum Team!
i've used `npm install --save v-tooltip`

and got  `"v-tooltip": "^3.0.0-alpha.21",`

seems this version has issues with classes, cause classes didn't set correctly, 
please update documentation! 

PS ` "v-tooltip": "@2.0.2",` works as expected

BR Yuriy

**Comment by Akryum** [comment]
Wrong dist tag was put on the alpha. :bow:
