### ISSUE TITLE
JavaScript critical error at line 25, column 48002 in https://unpkg.com/v-tooltip\n\nSCRIPT1003: Expected ':'

### ISSUE THREAD

**Issue by dn978** [Akryum/v-tooltip#656]
The tool tip failed on IE. it worked fine with Chrome and Edge. How do I get around the issue? I am using VueJS version 2.5.16

**Comment by yavisht** [comment]
@dn978 I can confirm this here's a temp fix - Lock versions

V-tooltip uses  ```vue-resize``` as a dependency. 
For now, downgrading the dependency versions fixed it for me, however its ideal to make it work with the latest release

```
"v-tooltip": "2.0.0-rc.33",
"vue-resize": "0.5.0",
```

**Comment by Akryum** [comment]
Duplicate of #615

**Comment by dn978** [comment]
I ended up going back to version prior to 2.10 and it worked without error. Thanks,
