### ISSUE TITLE
Margin not respected when placement changes direction

### ISSUE THREAD

**Issue by joelgenter** [Akryum/v-tooltip#68]
Hi,

This issue may only exist while in live-reload but I wanted to bring it to your attention anyway in case there are other implications. 

I have my popover styled as follows:
![image](https://user-images.githubusercontent.com/14948437/32963223-49a2993c-cb9d-11e7-977f-0d8ed200eae9.png)

While the popover is still open and I change the placement to "left" in the source code and save, the margin-right isn't respected:
![image](https://user-images.githubusercontent.com/14948437/32963346-a8a30296-cb9d-11e7-8892-811d4a5008c2.png)

When I refresh the page, the margin-right is respected:
![image](https://user-images.githubusercontent.com/14948437/32963420-de650a96-cb9d-11e7-873a-7adc7937abd8.png)

I'm using `"v-tooltip": "^2.0.0-rc.19"`.

**Comment by Akryum** [comment]
I can't reproduce in the demo anymore.
