### ISSUE TITLE
iOS Tap Behavior

### ISSUE THREAD

**Issue by ellisio** [Akryum/v-tooltip#7]
Using the following component causes the Tooltip to display when you tap the button. However, the tooltip does not disappear when tapping anywhere else on the screen. The only way to get the tooltip to go away is to refresh the page.

```vue
<template>
    <button v-tooltip.left-middle="content">Content</button>
</template>

<script>
    export default {
        data() {
            return {
                content: 'Hello'
            }
        }
    }
</script>
```

[Codepin Example](http://codepen.io/ellisthedev/pen/bgmyWz)

**Comment by Akryum** [comment]
This will be difficult for me to resolve since I don't have any Apple product for testing. :disappointed:

**Comment by brianjorden** [comment]
There is a pretty simple fix, but I can't re-submit my pull request today at the moment. Basically there is an option that can be added to the new tether call to allow the opening/closing to work on click OR hover. Further info here: https://github.com/HubSpot/tooltip/issues/9

**Comment by magbicaleman** [comment]
This is not limited to iOS, you can replicate it by using Chromes device toggle feature.

![image](https://cloud.githubusercontent.com/assets/735039/25852995/3db555a6-3499-11e7-9cf0-54a1ed71bfe3.png)

Open tooltip, and scroll and it will seem like it's fixed position.

**Comment by Akryum** [comment]
Please try the new beta to see if this is still an issue in iOS.

**Comment by Akryum** [comment]
Now fixed.
