### ISSUE TITLE
I Installed the plugin but nothing happens

### ISSUE THREAD

**Issue by nagyszem22** [Akryum/v-tooltip#70]
I did the following:

1.) npm install --save v-tooltip
2.) then imported it in my bootstrap.js file (this file initiates vue in my project)
      import VTooltip from 'v-tooltip';
      Vue.use(VTooltip);
      (of course Vue is defined, I import multiple other components in the same way)

Nothing happens, I don't get any error messages.

**Comment by Akryum** [comment]
Did you [add any style for the tooltips](https://github.com/Akryum/v-tooltip#style-examples)?

**Comment by R4meau** [comment]
I have the same problem and adding the styles myself doesn't work either. @Akryum Shouldn't it be done automatically?

**Comment by Akryum** [comment]
- What bundler are you using? Webpack?
- What is the result of `npm list v-tooltip`?
- Which version of Vue are you using?
- Is the tooltip HTML elements appearing in the `<body>`?
- Is the target element mouse-events disabled? (For example: `mouse-event: none;`)

**Comment by Akryum** [comment]
> @Akryum Shouldn't it be done automatically?

Automatically importing styles in a JS module is tricky, you never know if the package user will have the right build tools to allow that (I have tried it in the past for some of my packages, but now the user just have to include the CSS by himself the way he wants). Plus there is 99% chance you will change the CSS of the tooltips anyway.

**Comment by Akryum** [comment]
Could you also printing the result of `console.log(VTooltip)`?

**Comment by R4meau** [comment]
> What bundler are you using? Webpack?

Yes
> What is the result of npm list v-tooltip?

v-tooltip@2.0.0-rc.23 
> Which version of Vue are you using?

Vue v2.4.2
> Is the tooltip HTML elements appearing in the <body>?

I can see the code coming on and off from the console, but nothing visible.
> Is the target element mouse-events disabled? (For example: mouse-event: none;)

No.
> Could you also print the result of console.log(VTooltip)?

Here's what I get after running "console.log(\`FOO${JSON.stringify(VTooltip, null, 4)}BAR\`)" from my `mounted` lifecycle.

```js
FOO{
    "options": {
        "defaultPlacement": "top",
        "defaultClass": "vue-tooltip-theme",
        "defaultTargetClass": "has-tooltip",
        "defaultTemplate": "<div class=\"tooltip\" role=\"tooltip\"><div class=\"tooltip-arrow\"></div><div class=\"tooltip-inner\"></div></div>",
        "defaultDelay": 0,
        "defaultTrigger": "hover focus",
        "defaultOffset": 0,
        "defaultContainer": "body",
        "defaultPopperOptions": {},
        "autoHide": true,
        "disposeTimeout": 5000,
        "popover": {
            "defaultPlacement": "bottom",
            "defaultClass": "vue-popover-theme",
            "defaultDelay": 0,
            "defaultTrigger": "click",
            "defaultOffset": 0,
            "defaultContainer": "body",
            "defaultPopperOptions": {},
            "defaultAutoHide": true,
            "defaultHandleResize": true
        }
    }
}BAR
```

**Comment by Akryum** [comment]
> I can see the code coming on and off from the console, but nothing visible.

Nothing visible in the body?

![image](https://user-images.githubusercontent.com/2798204/33137417-31ededa0-cfa8-11e7-9be5-69b389b0d4b1.png)

> Here's what I get after running "console.log(`FOO${JSON.stringify(VTooltip, null, 4)}BAR`)" from my mounted lifecycle.

Could you do that just after the `Vue.use(VTooltip)` with `console.log(VTooltip)` directly?

**Comment by R4meau** [comment]
> Nothing visible in the body?

Nothing. I don't see this `.tooltip` div.

> Could you do that just after the Vue.use(VTooltip) with console.log(VTooltip) directly?

I'm using it in a component, not globally.

**Comment by Akryum** [comment]
Okay, so are you doing this?

```js
import { VTooltip } from 'v-tooltip'

export default {
  directives: {
    tooltip: VTooltip,
  },
}
```

**Comment by R4meau** [comment]
I tried using it globally as you said, still doesn't work. I did a `console.log` right after the `Vue.use(VTooltip)` and I get this:
```js
{
    "enabled": true
}
```

**Comment by R4meau** [comment]
> Okay, so are you doing this?

Yes, something like this:
```js
import { VTooltip, VPopover } from 'v-tooltip'

export default {
  directives: {
    tooltip: VTooltip
  },

  components: {
    'v-popover': VPopover
  }
}
```
I'm trying to use both the tooltip and the popover. None of them show up.

**Comment by Akryum** [comment]
Did you try updating to the latest Vue 2.5.x?

**Comment by R4meau** [comment]
I just upgraded to Vue 2.5.8. Still not working. However, now I'm seeing the `.tooltip` div in the body when I hover the target.

**Comment by Akryum** [comment]
Do you have a reproduction to share (repo for example)? If not, take a look at the [demo source](https://github.com/Akryum/v-tooltip/tree/master/demo-src) and compare with what you have.

**Comment by R4meau** [comment]
Too bad, it's legacy code so I cannot share more. I checked the demo source and it looks like I'm doing it right. I'm in a hurry so I'll check something else for now, which is gonna involve more work from me. Will come back here if I ever figure it out. Thanks for your time.

**Comment by R4meau** [comment]
Okay, I just figured out where the problem is. I'm just not sure how to fix it yet. It's actually loading the style automatically, I'm not sure why you want us to add it anyway. When I check the console, there's a default style on the tooltip class that sets the opacity to 0. When I change it to 1, it works fine, the tooltip shows up.

Normally it should set the opacity to 1 on hover. But it's not.

**Comment by Akryum** [comment]
Do you have bootstrap on the project?

**Comment by R4meau** [comment]
I do.

**Comment by Akryum** [comment]
*That's why I never use bootstrap.* So the bootstrap CSS may conflict then. You can check which file the CSS is coming from in the Chrome devtools on the tooltip. You can [override the `defaultTemplate`](https://github.com/Akryum/v-tooltip#global-options) to change the classes on the tooltips, and adapt [the CSS you need to add](https://github.com/Akryum/v-tooltip#style-examples) accordingly.

**Comment by Akryum** [comment]
To help check the CSS of the tooltips, you can open the **Sources** tab of the Chrome devtools, mouse over the tooltip target element, and the press F8 to pause the JS execution. There is also a setting to disable the "paused" overlay displayed on the page.

**Comment by R4meau** [comment]
Hmm, I'm guessing an option to change the tooltip class would be a great addition. That's definitely the error.

**Comment by Akryum** [comment]
For example:

```js
import { VTooltip } from 'v-tooltip'
VTooltip.options.defaultTemplate =
  '<div class="foo" role="tooltip"><div class="tooltip-arrow"></div><div class="tooltip-inner"></div></div>'
```

**Comment by R4meau** [comment]
This works fine, the basic tooltip shows up nicely now. But I'm using the popover, and even when this option is set, `VPopover` still uses the `tooltip` class. And VPopover doesn't accept options AFAIK. Do you have a solution for this?

**Comment by Akryum** [comment]
Override the bootstrap CSS for the popover.

**Comment by R4meau** [comment]
You mean, using `!important`?

**Comment by Akryum** [comment]
For now yes, but I will make some improvements for this use case (conflict with badly scoped CSS like bootstrap). :smile:

**Comment by Akryum** [comment]
https://github.com/twbs/bootstrap/blob/v4-dev/scss/_tooltip.scss

**Comment by R4meau** [comment]
Still won't work mate. :/ I added `!important` to every single line of CSS for the `tooltip` class.

**Comment by Akryum** [comment]
Bootstrap also set styles for `.popover`: https://github.com/twbs/bootstrap/blob/v4-dev/scss/_popover.scss

**Comment by R4meau** [comment]
I'm using the bootstrap-vue module. I made sure the whole project is not using the tooltip/popover plugins from Bootstrap. I'm going to cherry-pick the plugins I need and will take out the tooltip/popover ones. Thanks a lot for your help mate.

**Comment by Akryum** [comment]
Here is an example of style that reset most of the bootstrap CSS:

```stylus
.tooltip
  display block !important
  z-index 999999

  // Reset bootstrap
  &::before
    display none !important
  &::after
    display none !important

  .wrapper
    // Reset bootstrap
    max-width none
    margin 0
    padding 0

  &.popover
    // Reset bootstrap
    max-width none
    padding 0
    border none
    background-color transparent
    border-radius 0
    font-size 1em
    font-family inherit

    .popover-inner
      max-width none
```

(stylus)

**Comment by R4meau** [comment]
I believe an option to change the `tooltip` class would be a great plus for this module btw.

**Comment by R4meau** [comment]
> Here is an example of style that reset most of the bootstrap CSS

I did that. Wouldn't work for some reason.

**Comment by Akryum** [comment]
https://github.com/Akryum/v-tooltip/releases/tag/v2.0.0-rc.24

**Comment by ilyaDegtyarenko** [comment]
### First step:
```
import Vue from 'vue';
import VTooltip from 'v-tooltip';

Vue.directive('v-tooltip',  VTooltip);
```

### Second step:
> _Important: Not scoped styles._

```
<style lang="scss"> 
    .tooltip {
        &[aria-hidden='true'] {
            visibility: hidden;
            opacity: 0;
            transition: opacity .15s, visibility .15s;
        }

        &[aria-hidden='false'] {
            visibility: visible;
            opacity: 1;
            transition: opacity .15s;
        }

        /*Your styles.*/

        display: block !important;
        z-index: 10000;
    }
</style>

<style lang="scss" scoped>
    /*Other styles.*/
</style>
```

### Third step:
> _'v-tooltip' - yout directive._

`<div v-tooltip="'Hello. It\'s me...'">Hover me.</div>`

**Enjoy.**
