### ISSUE TITLE
Offset behaves oddly for negative values

### ISSUE THREAD

**Issue by flxsource** [Akryum/v-tooltip#71]
When using:

`{placement: 'bottom', offset: '10'}`

the tooltip is correctly placed 10px below the default position. However when using:

`{placement: 'bottom', offset: '-10'}`

the tooltip is placed approximately 20px above and 10px to the left of the default position - the expected position is 10px directly above the default position.

The tooltip also changes placement to top.

Using 2.0.0-rc.25

**Comment by Akryum** [comment]
I believe this is an issue with popper.

**Comment by Akryum** [comment]
You need to disable the `flip` modifier which is switching the position when the popper overlaps with the target:

```js
popperOptions: {
  modifiers: {
    flip: {
      enabled: false,
    },
  },
}
```

See [this issue](https://github.com/FezVrasta/popper.js/issues/373)
