### ISSUE TITLE
Error in documentation about defaultTrigger

### ISSUE THREAD

**Issue by VasiliyRusin** [Akryum/v-tooltip#723]
According to this [line](https://github.com/Akryum/v-tooltip/blob/master/src/directives/v-tooltip.js#L76), `defaultTrigger: 'click'`, but in [documentation](https://github.com/Akryum/v-tooltip#global-options) it's `defaultTrigger: 'hover focus'`

**Comment by Akryum** [comment]
What about [this line](https://github.com/Akryum/v-tooltip/blob/master/src/directives/v-tooltip.js#L43)? :smile_cat:
