### ISSUE TITLE
Incompatibilité avec IE11

### ISSUE THREAD

**Issue by MaximeAubry** [Akryum/v-tooltip#73]
Bonjour.

Certains événements ne fonctionnent pas avec IE11, tels que le hover.
Y aura t'il un correctif prochainement ?

Merci.

**Comment by Akryum** [comment]
Les événements comme `mouseover` sont supporté par IE. Avez-vous plus de détails ?

**Comment by MaximeAubry** [comment]
J'ai juste lancé votre live demo sur IE11 : [https://akryum.github.io/v-tooltip/#/](https://akryum.github.io/v-tooltip/#/)
Les 2 premiers exemples ne fonctionnent pas.
Message d'erreur dans IE11 :
L’objet ne gère pas la propriété ou la méthode « assign »
v-tooltip.esm.js (2925,4)

**Comment by Akryum** [comment]
Voir https://github.com/Akryum/v-tooltip/issues/24
