### ISSUE TITLE
v-tooltip removes any css class when added to <svg>

### ISSUE THREAD

**Issue by MaciejJanyska** [Akryum/v-tooltip#74]
Adding v-tooltip to the `<svg>` element causes a deletion of css class in svg.

Please look at this jsfiddle example: https://jsfiddle.net/njsyfnsp/1/

**Comment by jwkicklighter** [comment]
Also seeing this, was coming to create an issue myself.

**Comment by normelton** [comment]
Same here.

**Comment by vinayakkulkarni** [comment]
Ah yes! Got the same issue.. this is kinda a huge bug!
