### ISSUE TITLE
v-tooltip directive duplicates mountTarget

### ISSUE THREAD

**Issue by TadeasPopov** [Akryum/v-tooltip#746]
Hello,

when I am using v-tooltip directive, it creates element
```<div v-data-app></div>```
for each tooltip on my page and adds it to `document.body`.

I am not sure, if it is intended behaviour or if it is a bug, but it does not happen in Vue2 (I am using Vue3).
It also seems, that those elements are not used at all, because when I hover over some element with v-tooltip, it just creates a new `div` and destroys it afterwards, which does not happen for mentioned element above and it might leave a lot of unused elements in `body`.

EDIT:
I expect it happens over here:
https://github.com/Akryum/v-tooltip/blob/vue3/packages/v-tooltip/src/directives/v-tooltip.js#L60

**Comment by Akryum** [comment]
This is intended because each tooltip is a small Vue app.
