### ISSUE TITLE
Demande d'informations complémentaires

### ISSUE THREAD

**Issue by MaximeAubry** [Akryum/v-tooltip#75]
Bonjour.

J'aimerai savoir comment changer les options d'un popover svp.
Vous l'avez montré pour le tooltip :
`<button v-tooltip="options">`

Mais je ne trouve pas l'équivalent dans la doc pour l'autre composant.
Puis-je utiliser v-tooltip pour appliquer un template comportant des composants perso ?
Puis-je appliquer un template autrement que par la déclaration dans le json ?

`

<script type="text/x-template" id="hello-world-template">  <p>Bonjour bonjour bonjour</p></script>
--

`

Merci

**Comment by Akryum** [comment]
Contrairement à v-tooltip, v-popover est un composant Vue à part entière. Il a des [props](https://github.com/Akryum/v-tooltip#popover-component-reference) ([doc](https://fr.vuejs.org/v2/guide/components.html#Props)) pour le personnaliser et émet des événements. Pour lui ajouter du contenu, il faut utiliser ses [slots](https://fr.vuejs.org/v2/guide/components.html#Distribution-de-contenu-avec-des-slots).

Exemple:

```html
<v-popover offset="10">
  <button>Click me</button>

  <template slot="popover">
    <hello-world-component />
  </template>
</v-popover>
```

**Comment by MaximeAubry** [comment]
ok merci :)
