### ISSUE TITLE
click to trigger, mouseout to hide?

### ISSUE THREAD

**Issue by j3k2** [Akryum/v-tooltip#756]
i'd like to make a tooltip appear only when its target is clicked, and also for this tooltip to hide only when the mouse is moved away from its target. is this possible?

i tried using both hover and click for the trigger option, but this ultimately produces the opposite of what i want to achieve (hovering initially shows the tooltip, clicking then hides it).

ideally i'd be able to set different events to separate "showTrigger" and "hideTrigger" options

**Comment by Akryum** [comment]
It's possible with the new version of v-tooltip documented [here](https://v-tooltip.netlify.app)
