### ISSUE TITLE
Global Configuration Not Impacting Tooltip

### ISSUE THREAD

**Issue by LinnaeK** [Akryum/v-tooltip#767]
I am using your Vue 3 version of V-tooltip and have tried to change the delay in a v-tooltip boot file with the following code:

```
const options = {
    themes: {
      tooltip: {
        delay: { show: 5, hide: 1500 }
      }
    }
  }
  app.use(VTooltip, options)
  app.directive('tooltip', VTooltip)
```
  
  This is not impacting the tooltip.  However, if I add the delay in-line as follows it works:
  
  ```
button.cursor-pointer.ml-1(
   v-tooltip.bottom="{content: `Coaches: ${getCoaches(game.visitorTeam.coaches)}`,  delay: { show: 5, hide: 1500 }}"
)
```
  
  We need a similar change to configuration for each tooltip and would prefer to apply the change globally.  Are global configurations working with Vue 3? If so, how do I need to change our code in order to apply them? 

Thank you!

**Comment by runxc1** [comment]
Did you ever figure this out?

**Comment by Qonflux** [comment]
Also would like to know how to solve this!

**Comment by Akryum** [comment]
Could you please share a reproduction? This is working for me:

![image](https://user-images.githubusercontent.com/2798204/148376835-32fc2667-5225-4221-ae03-59f2c0d751c8.png)

**Comment by LinnaeK** [comment]
I reviewed your documentation and retested this and it is working now. Thank you for your response!
