### ISSUE TITLE
pb directive close

### ISSUE THREAD

**Issue by nlefebvre1410** [Akryum/v-tooltip#77]
hi,
the error :

> Failed to resolve directive: close-popover

vue version : 3.0.1
main.js :
```
import { VTooltip, VPopover } from 'v-tooltip'
Vue.directive('tooltip', VTooltip)
Vue.component('v-popover', VPopover)
```
help me !!!

**Comment by Akryum** [comment]
Make sure to put this code before creating your app. Also, Vue 3.0.1 doesn't exists.

**Comment by nlefebvre1410** [comment]
sorry  "vue": "^2.4.2",

**Comment by Akryum** [comment]
You need to declare it too:

```js
Vue.directive('close-popover', VClosePopover)
```

It was missing in the docs, which [is now fixed](https://github.com/Akryum/v-tooltip/blob/master/README.md#installation).
