### ISSUE TITLE
In 4.0.0-alpha.1 version it does not seem to respect to autoHide: false

### ISSUE THREAD

**Issue by damianosz** [Akryum/v-tooltip#778]
It keeps auto-hiding even with autoHide: false

**Comment by damianosz** [comment]
Not sure if is because in PopperWrapper.vue you use "auto-hide" instead of "autohide" when consuming <PopperConent>

![image](https://user-images.githubusercontent.com/87659139/127165690-4642e8cb-70b4-4484-ba0c-35cca4b15e58.png)

**Comment by damianosz** [comment]
Either way the v-tooltip always go away after a bit. They do not seem to respect autoHide false

**Comment by naaadz** [comment]
![image](https://user-images.githubusercontent.com/8333393/127555767-86e26d0b-23d0-48d1-9aef-57ef6f044f19.png)
autohide false doesn't work on the demo page https://v-tooltip.netlify.app/theme-editor.html

**Comment by damianosz** [comment]
@Akryum To be more precise, no longer respects autoHide: false like in the Vue 2 version. when using hover. But it does with click. We would like to make autoHide: false on hover as well.
I tried getting the Vue 3 source but I cannot seem to figure it out. I wonder if in the Vue 2 version you had a bit more code that still need to be carried over?

**Comment by Akryum** [comment]
When you use hover, it's normal for the tooltip to close on mouseout

**Comment by naaadz** [comment]
we use the autoHide:false option so we are able to hover over the tooltip itself if we need to copy text or click a link. Thats what is not working anymore.

**Comment by d-manevich** [comment]
Hi! Thanks for the great convenient tooltip!

Got the same issue. I have a button with a dynamic tooltip that changes when button is clicked. This causes the tooltip to close.
To fix this, for vue 2 I used manual hover trigger and autoHide: false. But in v4 for vue 3 this doesn't help anymore

**Comment by Akryum** [comment]
`autoHide` is unrelated then. It's an option that closes the popper when clicked outside of it.

**Comment by Akryum** [comment]
Set the triggers like this: https://github.com/Akryum/v-tooltip/blob/1b987c7a9db84407c6c9055be67bc093c42398b8/packages/v-tooltip/src/config.js#L57-L58
