### ISSUE TITLE
iPhone click seen as hover

### ISSUE THREAD

**Issue by MadReal** [Akryum/v-tooltip#78]
Hello, have you noticed the behavior of the tooltip on iPhone? It will prevent the click because on click it will first show the tooltip than you have to click again to actually do the action.

Do I have to configure something specific? Or what would be the best way to disable the tooltips on phone?

Thanks

**Comment by Akryum** [comment]
This is standard browser behavior on mobile. See [doc](https://github.com/Akryum/v-tooltip#disabling-tooltips) for disabling tooltips.
