### ISSUE TITLE
Tooltip can close while mouse is over it, making it difficult to interact with content within

### ISSUE THREAD

**Issue by akowalz** [Akryum/v-tooltip#789]
I'm having an issue when putting interactive content within tooltips. Sometimes you will move from the trigger element to the popover, but along your path may trigger the close of the tooltip. If you are using a hide delay, you can make it all the way to the popover element, ready to click the content, but then the tooltip disappears out from under your mouse. It seems ideally tooltips would not close if the mouse was over them, but I see this happening a lot.

Here is a [Codepen](https://codepen.io/akowalz/pen/gORrbBE) that demonstrates the issue. Move your mouse from the trigger towards the top link in the tooltip. If at any point your mouse went outside the trigger or popover areas (very likely if you took a straight-line path), the tooltip will disappear out from under your mouse.

Is there a way to make it so the close event is cancelled when the mouse enters the popover area? Or maybe some combination of parameters that would make this issue less prevalent? It's frustrating for users to need to trace an exact path from the trigger element, through the arrow/triangle, then into the tooltip, instead of being able to mouse directly into it while it is open.

Open to suggestions, thank you for any help.

**Comment by piotrku** [comment]
Yeah it is still buggy, sometimes stays, sometimes closes while mouse is over :(
Any solutions?

**Comment by piotrku** [comment]
Yeah found a solution upgrade to 3.x branch - VMenu type of tooltip solved my issue.

**Comment by Akryum** [comment]
In v3+ you can specify `popper-triggers` to handle those use cases.

**Comment by alextegus** [comment]
thanks - it looks like `popperTriggers="['hover']"` should solve this issue.

Any word on when v3 will be out of alpha? Would you recommend migrating now, or is the API still unstable?

**Comment by akowalz** [comment]
Great - it looks like [`popperTriggers="['hover']"`](https://v-tooltip.netlify.app/api/#component-props) should solve this issue for us.

Any word on when v3 will be out of Alpha? Would you recommend migrating now, or is the API still rather unstable?
