### ISSUE TITLE
Invalid prop: type check failed for prop "boundariesElement"

### ISSUE THREAD

**Issue by p-adams** [Akryum/v-tooltip#79]
I am trying out v-popover in a Vue project that uses webpack, and I am following along with the docs. When I try the v-popover examples in the browser they work fine, but when I try them in the webpack project I get this error `[Vue warn]: Invalid prop: type check failed for prop "boundariesElement". Expected Element, got String.` The popover works but I am not sure what is generating this error. 

I am using `Vue 2.3.3` and `v-tooltip version 2.0.0-rc.18`

**Comment by amybrowndesign** [comment]
@p-adams I'm having the same issue. Did you find a solution?

`defaultBoundariesElement: 'window'` works as intended but I get also get the console warnings.

```
[Vue warn]: Invalid prop: type check failed for prop "boundariesElement". Expected Element, got String.

found in

---> <VPopover>
       <Root>
```

If I change it from a string to `defaultBoundariesElement: window,` or `defaultBoundariesElement: this.window` or `defaultBoundariesElement: 'body'` then I get a similar console warning *and* it breaks the tooltip implementation.
