### ISSUE TITLE
Could not find a declaration file for TS in Vue3

### ISSUE THREAD

**Issue by Frankaus** [Akryum/v-tooltip#811]
Hello,

We use a lot v-tooltip within our web app and we wish to continue doing so while we migrate on Vue3 with TS.

I installed the v-tooltip v4, and when importing the VTooltip from 'v-tooltip' vscode reminds me that there is no declaration (.d.ts) file for TS. I tried importing some from npm by running `npm i --save-dev @types/v-tooltip` but there is none.

Does the type declaration file exist for the v-tooltip v4? If yes, where can I find? Else, is it planned for 2022?

Thanks,
Francesco

**Comment by profispojka** [comment]
+1 for this

**Comment by zynth17** [comment]
is this solved?
