### ISSUE TITLE
[v-popover] v2 - Give option to change trigger element to `span` instead of always `div`

### ISSUE THREAD

**Issue by ManasMadrecha** [Akryum/v-tooltip#812]
Hi, 

I am using Nuxt 2 + its markdown Content module. I use this `v-tooltip` plugin to add definitions, etc. inside the paragraph `<p></p>` itself. 

Currently, the `v-popover` component renders as 

```html
<div class="v-popover">
    <div class="trigger" style="display: inline-block;">
        content here
    </div>
</div>
```

So, having `div` inside `p` is wrong. It would be great if the component gave the option to change the tags of both the `div` of the `v-popover` component. The default value of this prop `el` can be `div`, but it can be any HTML tag, like `span` too.

E.g., 
```
<v-popper el="span"></v-popper>
```

You can do this using `component` component.
E.g., in the v-popover component's code, you can change the root tags to 

```html
<component :is="el" class="v-popover">
    <component :is="el" class="trigger">
        ... rest HTML here ...
    </component>
</component>
```

Kindly do the needful. Thanks for this cool plugin 😋

**Comment by Akryum** [comment]
In v3 and v4 the structure changed (only one `div`) and you can [create your own](https://v-tooltip.netlify.app/guide/custom-component.html).
