### ISSUE TITLE
Tooltip markup is added but the tooltips aren't displayed

### ISSUE THREAD

**Issue by egeersoz** [Akryum/v-tooltip#84]
Vue 2.5.8
v-tooltip 2.0.0 RC 25

I added v-tooltip to my project as per instructions:

```
import Vue from 'vue'
import VTooltip from 'v-tooltip'

Vue.use(VTooltip)
```

Then I added `v-tooltip` to a tag inside one of my components:

```
<h4 v-tooltip="{ content: 'These are your goals for the week.' }">Goals</h4>
```

When I view this in the browser, I see that the markup is added to the element:

```
<h4 class=" has-tooltip" aria-describedby="tooltip_0pjbcsxvql">Goals</h4>
```

However, mousing over this element does nothing.

**Comment by egeersoz** [comment]
Bleh, never mind. Didn't realize styling has to be defined manually.

**Comment by shershen08** [comment]
Had the same ) Maybe it's good to add to README, that basic markup is not provided
