### ISSUE TITLE
Allow tooltip to be visible always

### ISSUE THREAD

**Issue by ralts00** [Akryum/v-tooltip#88]
I'm using the tooltip on a button and I need the tooltip to be visible always, but the following is not working:

```javascript
<button v-tooltip="{ content: helpText, open: true}">
```
How can I make the tooltip always visible?

**Comment by Akryum** [comment]
https://github.com/Akryum/v-tooltip/releases/tag/v2.0.0-rc.27

**Comment by An-AngryBear** [comment]
@Akryum `v2.0.2`: the tooltip still hides if you hover over the element.

```html
v-tooltip.top="{
    content: progress + '%', 
    boundariesElement: '.content-container',
    show: true,
    autoHide: false,
}"
```

**Comment by martinszeltins** [comment]
> ```
> autoHide
> ```

5 years later, this is still broken 😞  Even if I set `autoHide: false` it still gets hidden if I hover.
