### ISSUE TITLE
No opacity transition when tooltip/popover appears for the first time.

### ISSUE THREAD

**Issue by Waals** [Akryum/v-tooltip#89]
When a tooltip or a popover is enabled for the first time, it appears suddenly, without any css transition.
I believe that's because the element is created directly in a visible state. It does not pass from an hidden state to a visible state.

After waiting a few seconds, the element is removed from the DOM, and the same behaviour happens again.

**Comment by Akryum** [comment]
Cannot reproduce on the demo: https://akryum.github.io/v-tooltip/#/
Make sure you have [the correct CSS](https://github.com/Akryum/v-tooltip#style-examples) and try to upgrade the plugin.
