### ISSUE TITLE
Add delay option

### ISSUE THREAD

**Issue by AsafAgranat** [Akryum/v-tooltip#9]
Would it be possible to add a tooltip delay option?
Thanks!

**Comment by Akryum** [comment]
Please try the new beta! :smile:

**Comment by rottmann** [comment]
Beta did not show me anything. No error, nothing.

**Comment by Akryum** [comment]
Did you update your CSS? Classes changed.

**Comment by rottmann** [comment]
Thanks, everything ok, did not see the new css-names.
