### ISSUE TITLE
Tooltip text blur cause of css transform property

### ISSUE THREAD

**Issue by arifhussain353** [Akryum/v-tooltip#91]
Tooltip text is blur because of `CSS` property ` transform: translate3d...`. Is there any alternative to this issue?

**Blur text tooltip: ** 

![image](https://user-images.githubusercontent.com/12670763/35089979-306acf5a-fc5a-11e7-8c7c-c1a31cb6a80e.png)

**Should be like this :** 

![image](https://user-images.githubusercontent.com/12670763/35090055-6b485dd6-fc5a-11e7-83e8-09f4cac4ab67.png)

**Comment by arifhussain353** [comment]
I am sorry. I didn't see my browser zoom in.

**Comment by bfic** [comment]
Any ideas how to solve it ?

**Comment by arifhussain353** [comment]
@bfic for me  it was not an issue because  my browser was on 90% zoom in.

**Comment by bfic** [comment]
LOL the same for me xD

**Comment by arifhussain353** [comment]
XD this what when you tired of doing  programing continuously. Happy coding!

**Comment by Diamanter** [comment]
Yes, would be better to use left-top for the position inside the component, browsers cheat when using translate3D
