### ISSUE TITLE
Overflow-x breaks position top/bottom

### ISSUE THREAD

**Issue by Aareksio** [Akryum/v-tooltip#92]
Regression in 2.0.0-rc.23

Something is wrong with position correction starting on rc23

rc22: https://jsfiddle.net/ecrba1ms/1/
rc23: https://jsfiddle.net/ecrba1ms/2/

**Comment by Akryum** [comment]
This seems to be an issue with Popper.js

**Comment by Aareksio** [comment]
I see popper bump from 1.12.6 to 1.12.9 in yarn.lock, could you please try to determine which of these versions introduced the issue?
