### ISSUE TITLE
Can <v-popover> be made hoverable ?

### ISSUE THREAD

**Issue by Waals** [Akryum/v-tooltip#94]
Now that we have a `<v-popover>` component, can we reconsider the feature [mentionned in this issue](https://github.com/Akryum/v-tooltip/issues/12) ?
On [the demo page](https://akryum.github.io/v-tooltip/#/), you show how to use `<v-popover>` with an interactive component and a 'click' trigger, but no interaction can be made when using the 'hover' trigger. 
What do you think ?

**Comment by Akryum** [comment]
See [this example](https://github.com/vuejs/vue-devtools/blob/master/src/devtools/components/DataField.vue#L3).

**Comment by Waals** [comment]
@Akryum, can you explain ? I tried to unterstand your example but I can't see how you achieve this behaviour.

**Comment by tombalev** [comment]
Remove offset from v-popover and offset it in CSS instead
``
.tooltip{
	border: none;
	background-color: transparent;

  &.popover {
    .popover-inner {
		margin-top: 30px;
    }
  }
}``

**Comment by gmask** [comment]
Hmm, I'm having this issue as well: I need the popover content to appear on hover, however it disappears as soon as the mouse cursor moves over the popover content. @tombalev unfortunately your solution isn't working for me as I still need the location to accept the position prop.

**Comment by kyalha** [comment]
@Baloche @benjivm  I am not sure why it hasn't be suggested but popover can accept properites such as: open.
So a simple way of making it working with VueJS,  would be:

<div class="m-auto cursor-pointer" @mouseover="tootlTipIsOpen = true" 
 @mouseleave="tootlTipIsOpen = false">
            <v-popover offset="0" :popoverClass="'tooltip-prices'" @mouseleave="tootlTipIsOpen = false" :open="tootlTipIsOpen">
              <div class="tooltip-target">
                <span>hover me !</span>
              </div>
              <template slot="popover">
                <img :src="/shoes.png" width="100%"/>
              </template>
            </v-popover>
          </div>

**Comment by HLXII** [comment]
Adding this as I also found a workaround similar to iconictb.

Following from the CSS example given in [the documentation](https://www.npmjs.com/package/v-tooltip#style-examples), there was styling to add margins to the tooltips:

``` CSS
.tooltip[x-placement^="top"] {
  margin-bottom: 5px;
}

.tooltip[x-placement^="bottom"] {
  margin-top: 5px;
}

.tooltip[x-placement^="right"] {
  margin-left: 5px;
}

.tooltip[x-placement^="left"] {
  margin-right: 5px;
}
```

This caused a gap between the target element and the tooltip, so hovering away from the target would hide the tooltip.

Instead, if we remove the margin from the `tooltip` styling, there won't be a gap and the user can move their mouse over the popover element.

Additionally, if you still want to keep some margins between the target element and the tooltip, you can add margins to the `tooltip/popover-inner` styling.
