### ISSUE TITLE
`v-tooltip.right` breaks after upgrading from 2.0.0-rc.25

### ISSUE THREAD

**Issue by JounQin** [Akryum/v-tooltip#95]
Version: 2.0.0-rc.25:

![jietu20180127-003904](https://user-images.githubusercontent.com/8336744/35450360-bb6edc62-02fa-11e8-91ca-d15afe06aa3d.gif)

From version: 2.0.0-rc.26:

![jietu20180127-004331](https://user-images.githubusercontent.com/8336744/35450490-2be941e4-02fb-11e8-8e6b-fdf714913f22.gif)

I'm sorry I can not provide a reproduction because it's a company project and I can not reproduce it in your default jsfiddle, but I downgraded from 2.0.0-rc.30 version by version and found out it breaks from `2.0.0-rc.26`.

**Comment by JounQin** [comment]
OK, I find out we can use `boundariesElement: 'viewport'` to prevent this issue.

**Comment by vinayakkulkarni** [comment]
This was really helpful!

Thanks @JounQin
