### ISSUE TITLE
Package size could be reduced

### ISSUE THREAD

**Issue by MarkRizun** [Akryum/v-tooltip#96]
Hi,

The size of the package installed on the disk could be reduced by around 40%. 
Specifically, the folder "coverage" takes 423 Kb out of 1.02 Mb. If I understand correctly, it contains results of code test coverage that are not necessary for the end user.

Is there a way to install the package without this folder?

Thanks in advance,
Mark

**Comment by anat** [comment]
Hi,

Here I have my main bundle (loaded on every page), the size taken by v-tooltip is a bit heavy.

![image](https://user-images.githubusercontent.com/652592/50085329-05aa2800-01fa-11e9-9b40-8f167830b654.png)

Can we reopen this feature ?

Have a nice day

**Comment by gertjanwytynck** [comment]
Any news on this?

**Comment by imacrayon** [comment]
I found that importing a single component instead of all of v-tootip still produces the same bundle size. Normally I think this should reduce the size of my bundle right?
```
import VTooltip from 'v-tooltip' // 56K

import { VPopover } from 'v-tooltip' // still 56K
```

**Comment by Akryum** [comment]
@imacrayon should be fixed in v3 alpha

**Comment by imacrayon** [comment]
@gertjanwytynck check the update above

@Akryum thank you for the update and all your great work!
