### ISSUE TITLE
Ignore "title" attribute and use "content" property only

### ISSUE THREAD

**Issue by leonardothizon** [Akryum/v-tooltip#97]
I didn't find a way to ignore the title attribute in HTML elements and use only the content property defined in tooltip configuration.
I have situations where the title attribute must be displayed along with tooltip, but with different information.

**Comment by Akryum** [comment]
I'm not sure to understand your use case/issue.

**Comment by leonardothizon** [comment]
Hi,
I guess this issue can be closed. I am not experiencing this problem anymore.
