### ISSUE TITLE
Hover bug with popover and tooltip

### ISSUE THREAD

**Issue by dimensi** [Akryum/v-tooltip#99]
When try to quickly navigate through the elements, the tooltip is not always closed.
[video](https://giphy.com/gifs/3o7WIpemBrhz31EXXq/html5)

**Comment by dawin09** [comment]
Same Issue

**Comment by loy6491** [comment]
Same Issue

**Comment by artfc** [comment]
If i understand correctly, the problem is at this line of code in Popover.vue:
```
// Show the tooltip
requestAnimationFrame(() => {
    if (!this.$_isDisposed) {
        this.isOpen = true // <======== hide() could be called while isOpen is not yet set
    } else {
        this.dispose()
    }
})
```

**Comment by magistr4815** [comment]
How to fix it? can I see an example?
When will fix this problem?

**Comment by phiterf** [comment]
Still happening

**Comment by Srg404** [comment]
Same issue too.
It's a huge problem for me do you think fix it in the early futur?

**Comment by 13VF** [comment]
I have a fix for this https://github.com/Akryum/v-tooltip/pull/165 , if you want to participate - write your comments.

**Comment by tdrach** [comment]
Having the same issue here, but temporarily solved it with: 

```
.tooltip[aria-hidden="true"] {
  opacity: 0;
  transition: .2s ease all;
}
```

`aria-hidden` is accurate when it needs to be, so you should be able to select with that if you need to.

**Comment by Akryum** [comment]
Cannot reproduce [on the demo](https://akryum.github.io/v-tooltip/#/table) since v2.0.0

**Comment by nntai** [comment]
I faced with this bug and temporarily fixed by setting `openGroup` to be row's id for each popover. You could have a performance issue when using this fix.
